examples/location-weather/src/index.ts
examples/postgres-geodb/.meshrc.yaml
examples/postgres-geodb/src/mesh/additional-resolvers.ts
examples/postgres-geodb/src/test.query.graphql
examples/postgres-geodb/src/test.ts
packages/cli/package.json
packages/cli/src/bin.ts
packages/cli/src/commands/generate-sdk.ts
packages/cli/src/commands/serve.ts
packages/cli/src/commands/typescript.ts
packages/handlers/mongoose/src/index.ts
packages/handlers/postgraphile/src/index.ts
packages/runtime/src/get-mesh.ts
packages/types/src/index.ts
yarn.lock

For both mongoose and postgraphile, now we have `destroy` method that emits `destroy` event so the event listeners close the db connections in order to prevent hanging issues.

Fix DB Connection Issues

---

README.md
examples/location-weather/src/index.ts
examples/postgres-geodb/src/test.ts
packages/cli/src/bin.ts
packages/runtime/src/parse-config.ts
packages/runtime/src/utils.ts

Related https://github.com/Urigo/graphql-mesh/issues/150
**BREAKING CHANGE:**
- `parseConfig` takes two parameters to parse the configuration file which has been already read. This function doesn't need NodeJS File System module (but uses module system to load packages and stuff)
`parseConfig(yamlString | jsonString | configObject, { configFormat: 'json' , 'yaml', 'object' })`
- `findAndParseConfig` finds and parses the configuration file using NodeJS File System.
- `processConfig` can be used for programmatic API which takes preloaded configuration object with preloaded handlers and transforms etc. It needs nothing from the platform it is running at such as File or Module System

Make runtime package browser friendly

---

packages/cli/src/bin.ts
packages/cli/src/commands/serve.ts

https://nodejs.org/api/cluster.html
This PR implements NodeJS Cluster support for GraphQL Mesh `serve` command. If no number specified, number of CPUs is used by default.
`yarn graphql-mesh serve --fork=<number-of-workers>`

Support cluster

---

packages/handlers/openapi/src/index.ts

Related: https://github.com/Urigo/graphql-mesh/issues/187

fix loading remote openapi schemas based on content-type

---

packages/handlers/openapi/src/index.ts
packages/handlers/openapi/yaml-config.graphql

Related https://github.com/Urigo/graphql-mesh/issues/198#issuecomment-610058320
Allow users to specify baseUrl to override server config for OpenAPI Handler

Allow users to specify baseUrl for OpenAPI Handler

---

examples/grpc-example/example-queries/GetMovies.query.graphql
examples/grpc-example/proto/Example.proto
examples/grpc-example/src/server.ts
packages/handlers/grpc/src/index.ts

for ... in will iterate over all entries on the prototype, which results in
enums getting numbered definitions.
e.g.
enum { ACTION = 0, DRAMA = 1 } will create a config with the values
ACTION, DRAMA, 0 and 1
Use Object.entries to only generate the enum config for ownProperties
of the enum proto object.

Fix grpc enum generation

---

examples/grpc-example/proto/io/xtech/service.proto
packages/handlers/grpc/src/index.ts

Use the original mehtod name to identify the type.
When the service names doesn't match the name in the config, the
service name is prepended to the method name. This results in query
methods incorrectly being identified as mutations.

Fix grpc method inference

---

examples/openapi-stackexchange/.meshrc.yml
examples/openapi-stackexchange/get-questions.query.graphql
examples/openapi-stackexchange/package.json
packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
packages/handlers/openapi/src/openapi-to-graphql/utils.ts
website/src/components/live-demo/index.js
yarn.lock

- If response code is `default`, pretend it is like `2xx`.
- If response content type definition has `json` in the mimetype, pretend it is `application/json`.
Related #248 and #355

Less strict validation for OpenAPI Handler

---

packages/cli/src/commands/serve/serve.ts

Pass an onOperation function when creating the subscription server,
so that when a subscription is initiated, we can pass the context.
This allows custom resolvers to be able to reference context and still
work when testing with the `graphql-mesh serve` command.

Fix playground WebSocket server

---

packages/handlers/grpc/src/index.ts
packages/handlers/mysql/src/index.ts
packages/handlers/odata/src/index.ts
packages/handlers/openapi/src/openapi-to-graphql/index.ts
packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
packages/handlers/openapi/src/openapi-to-graphql/preprocessor.ts
packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts
packages/handlers/openapi/src/openapi-to-graphql/utils.ts
packages/runtime/src/get-mesh.ts
packages/runtime/src/parse-config.ts
packages/runtime/src/resolvers-hooks.ts
packages/runtime/src/types.ts
packages/types/src/index.ts

Ignore GraphQLResolveInfo if `fields` option is defined in in-context sdk

---

.github/workflows/check-configuration.yml
examples/grpc-example/package.json
packages/handlers/postgraphile/package.json
packages/handlers/postgraphile/src/index.ts
packages/handlers/postgraphile/yaml-config.graphql
packages/types/src/config-schema.json
schema.graphql
website/docs/handlers/postgraphile.md
yarn.lock

**Breaking Change**
Remove `federation` option, you can add it by yourself. [See docs for more information](https://graphql-mesh.com/docs/handlers/postgraphile).
Related #583

Add support for PostGraphile plugins

---

packages/handlers/postgraphile/src/index.ts

The [sample for postgres](https://github.com/Urigo/graphql-mesh/tree/master/examples/postgres-geodb) did not work after downloading. After looking into why I discovered that is was due to the fact that when no plugins are provided undefined was passed into Promise.all which causes `getMeshSource` to fail.
Luckily only a very minor fix was needed.
Fixes #604

fix(postgraphile-getMeshSource): Fallback to empty array when no plugins

---

packages/cli/src/commands/scalars-map.ts
packages/handlers/grpc/package.json
packages/handlers/json-schema/package.json
packages/handlers/mysql/package.json
packages/handlers/mysql/src/index.ts
packages/handlers/odata/package.json
packages/handlers/odata/src/index.ts
packages/handlers/odata/test/__snapshots__/handler.spec.ts.snap
packages/handlers/openapi/package.json
packages/handlers/thrift/package.json
packages/handlers/thrift/src/index.ts
yarn.lock

`Byte`, `Date`, `Time`, `UtcOffset` and `Timestamp` have been recently added to graphql-scalars. So, Mesh now uses those scalars in the handlers to handle those specific types properly.

Use `Byte`, `Date`, `Time`, `UtcOffset` and `Timestamp` from graphql-scalars

---

packages/handlers/grpc/src/index.ts
packages/handlers/grpc/src/scalars.ts
packages/handlers/grpc/src/utils.ts
packages/handlers/grpc/test/fixtures/proto-tests/allvalues.proto
packages/handlers/grpc/test/fixtures/proto-tests/empty.proto
packages/handlers/grpc/test/fixtures/proto-tests/movie.proto
packages/handlers/grpc/test/fixtures/proto-tests/nested.proto
packages/handlers/grpc/test/fixtures/proto-tests/nopackage-nested.proto
packages/handlers/grpc/test/fixtures/proto-tests/outside.proto
packages/handlers/grpc/test/fixtures/proto-tests/underscores.proto
packages/handlers/grpc/test/handler.spec.ts
packages/handlers/grpc/test/scalars.spec.ts
packages/handlers/grpc/test/utils.spec.ts
packages/types/src/index.ts

**New Functionatlity**
- Protobuf supports an empty type, add support for those types in
graphql
- Protobuf messages can be defined in a nested way. Support this
nested way of defining and referencing proto messages.
**Refactor**
- Move helper functions to utils into their own file.
- Move scalar related stuff into it's own file. This will allow for
manipulating scalar mappings externally.
**Tests**
- Add helper function unit tests.
- Add tests for valid proto file use cases.

Add new grpc handler functionality, refactor and add tests

---

packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts
packages/handlers/openapi/test/__snapshots__/handler.spec.ts.snap
packages/handlers/openapi/test/example_api.test.ts

- Do not create enum types for integer because GraphQL doesn't support enums with numeric keys
- Use GraphQLBigInt for 64-bit integers instead of `GraphQLFloat`.

fix(openapi): handle integers better for enums and 64-bit values

---

.changeset/tiny-cherries-happen.md
packages/handlers/grpc/src/utils.ts
packages/handlers/grpc/test/handler.spec.ts
packages/handlers/grpc/test/utils.spec.ts

Should only be creating a `_` field for empty protos, not all proto
definitions.
- Add a test to verify the correct behavior
- Fix this oversight in `addInputOutputFields`

fix(handlers): grpc empty proto

---

website/docs/getting-started/basic-example.md
website/docs/getting-started/installation.md

Removes leading $ from commands so that the result of copy can be used directly.

fix(docs): Remove leading $ to fix copy

---

.changeset/nice-frogs-vanish.md
packages/handlers/openapi/src/index.ts
packages/handlers/openapi/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
packages/utils/src/read-file-or-url.ts

Related #955 
Some URLs don't have file extension or mime type information on HTTP headers. Now user is able to define `sourceFormat` in the configuration;
```
sources:
name: Kube
handler:
openapi:
source: http://localhost:8003/openapi/v2
sourceFormat: json
baseUrl: http://localhost:8003/
```

feat(openapi): add sourceFormat option to provide schema format explicitly

---

.changeset/tricky-queens-enjoy.md
packages/handlers/grpc/src/index.ts
packages/handlers/grpc/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts

Allow GRPC connections to go over https. Previously this would only
happen when a root CA was provided. There are cases where instead of
providing a root CA, a CA like letencrypt is used to validate the
cert authority. In this case we want to create a secure connnection
by calling `createSsl` without any options.
This can now be done via the config option `useHTTPS`.

feat(grpc): add https connection config

---

.changeset/warm-monkeys-dance.md
packages/handlers/openapi/src/index.ts
packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts
packages/handlers/openapi/test/example_api_combined.test.ts
packages/handlers/openapi/test/fixtures/example_oas_combined.json
packages/handlers/openapi/test/handler.spec.ts
packages/handlers/openapi/yaml-config.graphql
packages/types/src/config.ts

This pull request includes two fixes:
* limit argument will be generated for composed types (allOf, anyOf, oneOf)
* limit value is not mandatory for generated argument
And includes also a new feature:
* New config option `addLimitArgument` to be disable this argument generation, default value is true.`

OpenAPI: fix and tune add limit argument

---

.changeset/brave-jars-destroy.md
packages/handlers/grpc/src/index.ts

Changed graphql `schemaComposer` for RPC methods starting with `list` to `schemaComposer.Query`.

feat: schemaComposer.Query for RPC methods starting with list

---

.changeset/silent-wasps-roll.md
packages/handlers/mysql/package.json
packages/handlers/mysql/src/index.ts
packages/handlers/mysql/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts

feat(mysql): add an ability to use existing Pool instance

---

.changeset/clever-files-arrive.md
packages/cache/redis/src/index.ts

fix(redis-cache): stringify before saving values

---

packages/cli/src/commands/serve/yaml-config.graphql

This is a valid config:
```
origin: '*'
```

origin: '*' is a valid config

---

.changeset/eight-taxis-mate.md
packages/handlers/grpc/yaml-config.graphql

According to https://developers.google.com/protocol-buffers/docs/proto3#default, default values should not be serialized:
> Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.
This causes things like empty arrays, false values, etc to all come back as `null` from the mesh as they are not present in the response from gRPC. This can be fixed by passing `defaults: true` to proto-loader but this results in a config validation warning:
> ```
> GraphQL Mesh Configuration is not valid:
> data.sources[0].handler.grpc.protoFilePath.load should NOT have additional properties
> ```

Add defaults to gRPC LoadOptions

---

.changeset/dirty-geese-chew.md
packages/transforms/filter-schema/src/index.ts
packages/transforms/filter-schema/test/transform.spec.ts

Allows to filter schema types.
How it works:
* if filter does not contain a `.` it filters the type matching the pattern using `FilterTypes`.
* if it does contain a `.` the behavior is the same as previous.
Previous behavior was to fail on `fixedFieldGlob.contains` when `.` wasn't specified.

feat: allow to filter by type

---

.changeset/six-camels-study.md
packages/handlers/openapi/package.json
packages/handlers/openapi/src/index.ts
packages/handlers/openapi/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/docs/handlers/openapi.md

This PR exposes `genericPayloadArgName` and `selectQueryOrMutationField` from OpenAPI-to-GraphQL handler through Mesh YAML config.
When true, `genericPayloadArgName`, allows setting argument name for mutation payload to `requestBody`. If false current behavior will continue to have default camelCased pathname.
This can really help when dealing with APIs that infer long classes names that make arguments required in GraphQL queries unreadable and so unfriendly as well.
Ultimately it can be helpful and seen as an alternative solution to #1422.
`selectQueryOrMutationField` is the thing any OpenApi user needs.
It allows to explicitly override GET/POST operations from Query to Mutation and vice versa; it effectively addresses #1113.
The current API for this is probably not the nicest but it …

Extend OpenApi handler functionalities

---

packages/transforms/filter-schema/src/FilterObjectFieldsAndArguments.ts
packages/transforms/filter-schema/src/FilterRootFieldsAndArguments.ts
packages/transforms/filter-schema/src/common.ts
packages/transforms/filter-schema/src/filter-arguments.ts
packages/transforms/filter-schema/src/index.ts
packages/transforms/filter-schema/test/transform.spec.ts

This PR is work in progress.
Some comments:
- Argument filtering is implemented unit test run through I'm planning to add more cases before the PR
- Changes to the micro syntax and how its parsed
- Previously there were a max of 2 levels of information
- type or root field
- and the fields on the above
- Now there is (potentially) a third level
- arguments on the individual fields
- This required a significantly higher complexity in parsing the second and third level
- this is done by a couple of regex which also take into account glob pattern syntax to ensure this stays intact
Limitations:
- filtering of arguments is only possible when field name is explicitly supplied
-  `Query.{user(!pk),book}` works
-  `Query.{user(!{pk, name}),book}` works
-  `Query.{u*(!pk),book}` does **not** work …

Filter arguments

---

website/README.md

Added instructions:
- Use `--ignore-engines` when using node versions greater than `14.0`
- You need python 2.x as the dependency without which the pre-gyp build would fail (https://github.com/Urigo/graphql-mesh/issues/1543)

Updating website README to reflect the fixes made in issue #1543

---

.changeset/itchy-elephants-attack.md
examples/json-schema-subscriptions/.meshrc.yml
examples/json-schema-subscriptions/README.md
examples/json-schema-subscriptions/example-queries/todos.query.graphql
packages/cli/src/commands/serve/graphql-handler.ts
packages/cli/src/commands/serve/serve.ts
packages/config/src/index.ts
packages/config/yaml-config.graphql
packages/runtime/package.json
packages/runtime/src/get-mesh.ts
packages/runtime/src/types.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
packages/types/src/index.ts
website/docs/recipes/as-gateway.md
website/docs/recipes/federation.md
website/docs/recipes/live-queries.md
website/docs/recipes/subscriptions-webhooks.md
website/docs/transforms/resolvers-composition.md
website/sidebars.js
yarn.lock

Based on the amazing work at https://github.com/n1ru4l/graphql-live-query
Configuration:
```yml
liveQueryInvalidations:
- field: Mutation.addTodo
invalidate: 
- Query.todos
- field: Mutation.editTodo
invalidate:
- Todo:{args.id} # Invalidates updated Todo
```
And query;
```graphql
query getTodos @live {
todos {
...
}
}
```

feat(runtime): Live Queries Support

---

examples/federation-example/package.json
examples/federation-example/sandbox.config.json

Add delay to start gateway after services
Fix sandbox.config.json updating to node 14 as a dependency.
Add delay-cli package to create a run-task with a short 1s sleep before starting the gateway.
Add run-task to start services and gateway-delayed.
Fixes #1589 
https://codesandbox.io/s/graphql-mesh-federation-sample-nficv
Manually in the sandbox above. 1s delay might not be enough on slow machines though. Better than a broken sandbox in any case.
- OS: Windows 10/MacOS Big Sur
- `@graphql-mesh/...`: examples/federation-example
- NodeJS: 14
None

Fix federation example codesandbox

---

packages/transforms/filter-schema/src/bareFilter.ts
packages/transforms/filter-schema/src/wrapFilter.ts
packages/transforms/filter-schema/test/transform.spec.ts
website/docs/transforms/filter-schema.md

As per #1605, this PR introduces declarative syntax for filtering Types.
This is still backward compatible with previous syntax. Comments have been added to remind removing this support in next major release.
Motivation explained in #1605
Previous syntax (could only address one type per string)
```yaml
transforms:
- filterSchema:
filters:
- "!User"
```
New syntax (multiple types and potentially regex as well)
```yaml
transforms:
- filterSchema:
filters:
- Type.!{User, Post}
```
Introduced new unit tests to cover both old and new syntax on bare and wrap transform mode.

Introduce new declarative syntax for filtering Types

---

.changeset/moody-suns-bow.md
packages/cli/src/index.ts

As per #1696, this PR fixes how Mesh CLI is using base-dir.
In fact, this should be used only for anything relative to Mesh Config file; whilst options like `output` should have CWD as base.
Tested CLI commands relying on `output` option.
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] Any dependent changes have been merged and published in downstream modules~

Fix CLI usage of base-dir

---

.changeset/serious-hats-sniff.md
packages/handlers/openapi/src/index.ts
packages/handlers/openapi/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts

Allow for inline injection of the OpenAPIHandler spec via source as object.
For motivation see https://github.com/Urigo/graphql-mesh/issues/1747
It's not beautiful, feel free to solve this in a better way! I came up with this while taking a first look at the code, it fixed my blocker.
Partially Related #1747 
- [?] This change requires a documentation update
Please describe the tests that you ran to verify your …

OpenAPI allow source spec inline injection

---

.changeset/loud-coats-think.md
packages/cli/src/index.ts

Quick one-line fix.
In #1820 you have introduced introspection cache functionality, as discussed before.
However, as suggested in [PR review](https://github.com/Urigo/graphql-mesh/pull/1820/files#r598774580), we should use `baseDir` for the `introspectionCache` file and not `process.cwd()`.
This is because the file path is defined in Mesh Config file, and not as a command argument.
Anything inside the Mesh Config file should always be relative to the `baseDir` the same Config file lives in.

use baseDir for path defined in config file

---

.changeset/wicked-jobs-knock.md
website/docs/recipes/introspection-cache.md
website/sidebars.js

As per title,
this PR adds documentation on the Mesh website for the introspection-cache functionality recently introduced.

Document newly added introspection-cache functionality

---

packages/handlers/grpc/test/utils.spec.ts
packages/handlers/openapi/test/docusign.test.ts
packages/handlers/openapi/test/example_api.test.ts
packages/handlers/openapi/test/example_api2_server.ts
packages/handlers/openapi/test/example_api3.test.ts
packages/handlers/openapi/test/example_api3_server.ts
packages/handlers/openapi/test/example_api5_server.ts
packages/handlers/openapi/test/example_api6.test.ts
packages/handlers/openapi/test/example_api6_server.ts
packages/handlers/openapi/test/example_api_server.ts
packages/transforms/cache/test/cache.spec.ts
packages/transforms/encapsulate/test/encapsulate.spec.ts
packages/transforms/filter-schema/test/transform.spec.ts
packages/transforms/mock/test/mocking.spec.ts
packages/transforms/naming-convention/test/naming-convention.spec.ts
packages/transforms/prefix/test/prefix.spec.ts
packages/transforms/rename/test/wrapRename.spec.ts
packages/transforms/resolvers-composition/test/transform.spec.ts
packages/transforms/snapshot/test/snapshot.spec.ts

A number of unit tests contained minor errors (mostly typing and missing parameters). These are resolved now.
Fixes #1901
All existing unit tests were successfully executed.
- OS: Windows
- NodeJS: 12.18.3
It might be worth adding the appropriate transforms to the jest config to ensure unit tests fail when such errors are checked in.

Fixed minor errors in unit tests (mostly typing)

---

packages/transforms/resolvers-composition/src/index.ts
packages/transforms/resolvers-composition/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/docs/getting-started/mesh-transforms.md
website/docs/transforms/resolvers-composition.md

As per the title, this PR introduces "wrap" mode to the resolvers-composition transform.
This is in order to make this transform work on GraphQL sources.
The PR is related to#1891.
I tested the changes and updated and extended the documentation.
I introduced a new syntax for the transform but also kept backward compatibility with the previous syntax, this is in line with other transforms that support both "bare" and "wrap" modes.
The new syntax is as follow, note the new "mode" property, and the array that is now wrapped under "compositions" property:
```yml
transforms:
- resolversComposition:
mode: bare | wrap
compositions:
- resolver: 'Query.me'
composer: is-auth#isAuth
- resolver: 'Mutation.*'
composer: is-admin#isAdmin
```
This transform didn't support "wrap" mode prior to this PR. …

Add wrap mode to resolvers-composition transform

---

.changeset/tricky-eyes-sneeze.md
packages/transforms/cache/src/compute-cache-key.ts
packages/transforms/cache/test/cache.spec.ts

Cache transform does not respect subfield arguments.
Related #1976 
- OS: macOS Big Sur
- @graphql-mesh/transform-cache: v0.8.39
- NodeJS: v15.11.0

Ensure cache transform respects subfield arguments.

---

.changeset/healthy-dots-fail.md
packages/handlers/grpc/src/index.ts
packages/handlers/grpc/src/patchLongBits.ts

fix(grpc): apply patch to protobufjs to support bigint

---

.changeset/twelve-vans-enjoy.md
packages/handlers/openapi/package.json
packages/handlers/openapi/src/index.ts

Currently, the OpenAPI handler uses `loadsh` to build the object for selectQueryOrMutationField option to be passed to `openapi-to-graphql`.
The problem is that `loadsh`'s `set` has a nesting behavior which, for example, nests fields splitting by a “dot” character.
When you have a configuration like this:
```yaml
selectQueryOrMutationField:
- title: "Weather Service v1.0"
path: /weather/current
method: post
type: Query
- title: "Weather Service v1.0"
path: /weather/forecast
method: get
type: Mutation
```
It gets currently parsed by `lodash` like this:
```json
"selectQueryOrMutationField": {
"Weather Service v1": [
{
"/weather/current": {
"post": 0
},
"/weather/forecast": {
"get": 1
}
}
]
},
```
Whilst it should be parsed as follow:
```json
"selectQueryOrMutationField": {
"Weather Service …
```

Fix object nesting for selectQueryOrMutationField option on openAPI handler

---

.changeset/hip-flies-visit.md
packages/transforms/encapsulate/src/index.ts
packages/transforms/encapsulate/test/encapsulate.spec.ts

Sorry for skipping issue.
encapsulated schema fails to introspect if applyTo.{type} is true but {type} does not exist.
I had this problem in production and fixed it through patching node_modules. Commiting here a failing test first.
- OS: MacOS 11.2.3
- `@graphql-mesh/*`: master
- NodeJS: v14.16.0

fix(encapsulate): ignore type not defined

---

.changeset/tidy-mangos-cheat.md
packages/transforms/encapsulate/src/index.ts

#2021 introduce a new bug because request/result transforms were missed.
I'm not sure this is a good implementation.. this quite rely on lifecycle to get schema. But I don't know how can we get originalWrapSchema from transformRequest/transformResult without them...

fix(encapsulate): follow up fix #2021

---

.changeset/hot-onions-kneel.md
packages/cli/package.json
packages/cli/src/commands/serve/playground.ts
packages/cli/src/commands/serve/serve.ts
yarn.lock

- Pass `subscriptionEndpoint` to GraphiQL explicitly
- Pass schema into `useServer` function of the `graphql-ws` that sets up the ws endpoint
Fixes #2055
- OS: Windows / WSL (Ubuntu)
- `@graphql-mesh/latest`:
- NodeJS: 14.16.1
- [] I have commented my code, particularly in hard-to-understand areas

Subscription Fixes

---

website/docs/recipes/typescript.md

First, before the CLI command can be executed, the `require: -ts-node...` should be in the .yaml file, thus I've moved it above the CLI step.
Second, the API here only describes how to generate Typescript types for the entire schema. From this API it is clear that that is the only option available, and the description should be clear on that part. 
If, however, it is possible to do achieve more, then please clarify that in the documentation.
Fixes # https://github.com/Urigo/graphql-mesh/issues/1919
- OS:
- "@graphql-mesh/cli": "0.26.2",
- "@graphql-mesh/graphql": "0.15.2",
- "@graphql-mesh/openapi": "0.13.3",
- "@graphql-mesh/runtime": "0.12.0",
- "@graphql-mesh/transform-mock": "0.8.5",
- NodeJS:

Make documentation more precise and correct the order of steps.

---

website/docs/transforms/mock.md

The example is in both javascript and typescript versions.
Improving the documentation.
I believe all documentation examples should have typescript support. It could be a tabbed solution like many other documentations do.

Provide explanation for the mocked return value and an example

---

website/docs/transforms/mock.md

Also, adjust the rest of the mock documentation to be more coherent.
Fixes https://github.com/Urigo/graphql-mesh/issues/2014
It would be nice if the typescript documentation would become a first-class citizen.
Also, I believe the graphql-mesh should be treated as the primary library, not just a collection of other libraries, meaning the documentation should be complete for the use cases that graphql-mesh handles without the need to decipher the API of the lower-level libraries. (e.g. graphql-tools)

Extend documentation to for the usage of the `initializeStore` property

---

packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts

Fixes #2265
When logging the internal API call that was called for a query it has falsy values as well.
- OS: MacOS 11.4
- `@graphql-mesh/openapi`:
- NodeJS: v16.4.2

Fix issue with falsy values getting skipped when translated to REST calls.

---

.changeset/slow-carrots-relax.md
examples/odata-trippin/tests/__snapshots__/odata-trippin.test.js.snap
packages/handlers/odata/src/index.ts
packages/handlers/odata/test/__snapshots__/handler.spec.ts.snap
packages/handlers/odata/test/handler.spec.ts

I added test cases in the OData handler to verify that fields generated for bound functions have arguments corresponding to the function parameters and that requests that include functions generate OData urls with the appropriate arguments passed.
I've also fixed the issue by making the following changes:
- register the bound field corresponding to the function on the GraphQL schema only after adding all the parameters to to the arg. The old code has bug here, it was registering the arguments outside the loop that processes the arguments, and it was registering the function field inside …

OData handler: fix handling of bound functions with arguments

---

.changeset/light-lizards-applaud.md
packages/handlers/odata/test/custom-fetch.ts
packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
packages/handlers/openapi/test/example_api.test.ts
website/docs/handlers/openapi.md

OpenAPI handler allows setting a custom Fetch function.
This currently receives only URL and options.
With this PR I'm extending the arguments to also receive the context object.
Values available in the context can be used by developers to customise their handling in the fetch function.

Pass context as optional 3rd argument to OpenAPI custom fetch function

---

.changeset/itchy-bulldogs-joke.md
packages/transforms/rename/src/bareRename.ts
packages/transforms/rename/src/wrapRename.ts
packages/transforms/rename/test/__snapshots__/wrapRename.spec.ts.snap
packages/transforms/rename/test/wrapRename.spec.ts
packages/transforms/rename/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts

In order to enhance pattern matching when renaming types and fields as mentioned in #2469, @ntziolis and I discussed the issue and want to introduce an optional config option `regExpFlags` in which the flags to use for a pattern can be specified.
Like:
```yaml
- rename:
mode: wrap
renames:
- from:
type: Api(.*)
to:
type: $1
useRegExpForTypes: true
regExpFlags: g
```
Example use cases:
- Eliminating a certain substring (or even a bunch) from type and field names:
```yaml
- rename:
mode: wrap
renames:
- from:
type: Api|This|That(.*?)
to:
type: $1
useRegExpForTypes: true
regExpFlags: g
```
- Dropping suffixes:
```yaml
- rename:
mode: wrap
renames:
- from:
type: (.*)v\d+$
to:
type: $1
useRegExpForTypes: true
regExpFlags: i
```
Since `regExpFlags` is optional, nothing will break. Instead, the …

Enable flags for regular expressions in rename transform

---

.changeset/fluffy-years-prove.md
packages/utils/src/load-from-module-export-expression.ts

This PR fixes the cli definition of `syncImportFn`.
This currently uses createRequire to also support ESM.
The problem is that it passes a filename, to construct the require function, that does not exist.
In fact, `join(baseDir, 'mesh.config.js')` will never exist because `mesh.config.js` is not written as an artifact; since the config is printed within the module, both CommonJs (index.js) and ESModule (index.mjs).
`createRequire` does not necessarily need an actual "file" name, but it can also take a path.
This fix will pass the baseDir as the path argument, which will work both js and mjs.
Fixes #2610

fix cli imports

---

.changeset/happy-lions-play.md
packages/cli/src/commands/serve/serve.ts

Spread the [`ConnectionInit.payload` (aka `connectionParams`)](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#connectioninit) values in the WebSocket [HTTP Upgrade request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade) headers for a non-breaking fix of lacking authentication requirements.
Even through tampering with original request's headers feels illegal, it should be considered safe in this case since browsers dont allow specifying custom upgrade request header values when initialising a WebSocket connection. Because of this, passing along necessary header-like information is recommended to be done through the first WebSocket message inside an established connection, making the `connectionParams` synonymous to the upgrade request headers.
**Note:** …

fix(cli/serve): Spread WebSocket `connectionParams` to upgrade request headers

---

.changeset/mean-experts-argue.md
packages/cli/src/commands/ts-artifacts.ts
packages/cli/test/commands/fixtures/simple-compilation/.gitignore
packages/cli/test/commands/fixtures/simple-compilation/index.ts
packages/cli/test/commands/ts-artifacts.spec.ts

Adds new test cases to demonstrate the bug causing code generation to fail on Windows. The bug is caused by comparing paths with different path separators (`/` and `\`).
Fixes the issue by normalizing paths before comparing them.
Fixes #2650 
- OS: Windows 10
- `@graphql-mesh/cli`: 0.34.2
- NodeJS: 14.7.3
If this is a relatively large or complex change, …

Fix code generation failure on Windows

---

.changeset/cool-mugs-laugh.md
examples/postgres-geodb/.meshrc.yaml
packages/config/yaml-config.graphql
packages/runtime/src/get-mesh.ts
packages/transforms/federation/src/index.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
packages/utils/src/resolve-additional-resolvers.ts

Allows richer use of `keyArgs` for queries other than those that return lists (such as `Collection`s) and for more complex argument structures, such as passing keys to nested fields in an argument object.
Related https://github.com/Urigo/graphql-mesh/issues/2680
Please delete options that are not relevant. **Currently unsure of the nature of this change**
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by …

Allowing nested key args

---

.changeset/thirty-masks-cheer.md
packages/transforms/filter-schema/src/bareFilter.ts
packages/transforms/filter-schema/test/transform.spec.ts
website/docs/transforms/filter-schema.md

With this PR I want to add support for the following syntax on the filter transform:
`Query.*.!{id, name}`, `Query.*.{id, name}` and similar.
You can also see updated docs for other examples of supported syntax, but the key point is to target all fields in Type with `Type.*.`
This seems to be working for free with `wrap` mode, but it currently doesn't work with `bare` mode.
This PR intentionally adds support for this syntax and also provides relevant examples in the documentation.
4 new unit tests have been introduced.
Also, all tests for the filter transform have been fixed as they had TS errors.

Add support for fields wildcard when filtering for arguments

---

website/docs/recipes/as-gateway.md

Removed broken link and fixed grammar in "as-mesh" recipe docs.
Visually.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Remove broken self-referential link in "as-mesh" recipe docs.

---

.changeset/gold-points-drive.md
packages/handlers/openapi/src/index.ts
packages/handlers/openapi/yaml-config.graphql
packages/types/src/config.ts

Expose provideErrorExtensions to openapi config to align with the options given to the function `createGraphQLSchema` in /packages/handlers/openapi/src/openapi-to-graphql/index.ts
Allow disabling of automatic wrapping of errors into graphqlError objects

expose provideErrorExtensions config for openapi

---

.changeset/real-icons-lie.md
packages/transforms/naming-convention/src/index.ts
packages/transforms/naming-convention/test/naming-convention.spec.ts

feat(naming-convention): ignore fields needed by Federation spec

---

.changeset/silent-cherries-taste.md
packages/transforms/rename/src/wrapRename.ts
packages/transforms/rename/test/__snapshots__/wrapRename.spec.ts.snap
packages/transforms/rename/test/wrapRename.spec.ts

When using `rename` with a `useRegExpForFields` option, the rename transform is applied to all types of the schema (even with `type` specified), making some fields disappear. 🕳️  (cf: https://github.com/Urigo/graphql-mesh/issues/3437#issuecomment-1012199229)
Related #3437
A failing unit test has been added.

fix(transforms/rename): renaming fields should only affect specified `type`

---

examples/openapi-stackexchange/list-questions.query.graphql
website/docs/getting-started/basic-usage.mdx

This was a little frustrating to be a new user and to see typos in code (probably references to old code), followed directly by an example that didn't work.
I documented the heck out of this minor typo and one-line example change in the issues I opened.  Please let me know if you want me to change anything, or explain further.
Fixes:
1. Fixes  #3536 Updated references from "wikipedia" to "stackoverflow".  
2. Fixes #3537 Updated docs and example queries from "listQuestions", which no longer exists, to
"listUnansweredQuestions".  
Current Sandbox:
https://codesandbox.io/s/github/Urigo/graphql-mesh/tree/master/examples/openapi-stackexchange
Expected Sandbox (this PR that you are viewing):
https://codesandbox.io/s/github/rot26/graphql-mesh/tree/fix-basic-usage-example/examples/openapi-stackex …

Update basic usage example query: docs and example

---

.changeset/cold-dingos-prove.md
packages/cli/src/commands/serve/serve.ts

The following configuration is not spawning the expected 1 child process but [CPU numbers] processes:
```yaml
serve:
fork: 1
```
Fixes #3470
I did a test with my `spotify-graphql` Mesh server using `@graphql-mesh/cli@0.48.1-alpha-d3d7d124f.0` with the following configurations:
- `fork: 1` ✅ 
- `fork: 2` ✅ 
- `fork: true` ✅ 
- `fork: false` ✅

fix(server): fork=1 should spawn 1 child process

---

renovate.json

This The Guild preset configures:
- extend `config:base`
- automerges unless major
- add `dependencies` label to PR
- group all non-major updates into a single PR
- Higher priority to `@the-guild/*` and `@guild-docs/*` package (website related)
- + GraphQL mesh specific config (`ignoredDeps`)

chore(renovate): use common renovate config

---

.changeset/friendly-numbers-carry.md
packages/cli/src/config.ts

Adds `.${configName}rc.ts` as a valid search place for cosmiconfig.
Fixes #3587

feat(cli): add ts files as search place for config

---

.changeset/yellow-cobras-peel.md
packages/transforms/federation/src/index.ts

In the transformSchema function we initialize field name before use.
We try to federate two subgraphs which we generate using graphql-mesh. During the process of building the federated schema we encountered the error.
Fixes #3655
https://codesandbox.io/s/graphql-mesh-ydfpg3?file=/package.json
We tested it during the development of our federated graph.
- OS: MacOS/Windows/Linux
- `@graphql-mesh/transform-federation: 0.8.19`
- NodeJS: v14.18.3

fix(federation-transform): initialize field name before use

---

.changeset/tough-owls-agree.md
packages/transforms/rename/package.json
packages/transforms/rename/src/bareRename.ts
packages/transforms/rename/test/bareRename.spec.ts

This PR provides feature parity between the `wrap` and `bare` modes of the Rename Transform.
In `wrap` mode you could already rename argument names, in `bare` mode this wasn't possible and it will be possible after merging this PR.
`bare` mode didn't have any test so I have introduced all tests available for `wrap` mode into the `bare` mode version of the transform.

Add feature to rename arguments on Rename Transform 'bare' mode

---

.changeset/thick-bikes-fold.md
packages/store/src/index.ts

Fix issue with Shopify GraphQL Schema that contains illegals characters in GraphQL _StringValue_ (repro: https://github.com/Drew-Garratt/mesh-test)
Example invalid GraphQL definition:
```graphql
"""An article in an online store blog."""
type Article implements HasMetafields & Node & OnlineStorePublishable {
): MetafieldConnection! @deprecated(reason: "The `metafields` field will be removed in the future in favor of using [aliases](https://graphql.org/learn/queries/#aliases) with the `metafield` field.\n")
```
The `\n` in `@deprecated` `reason` argument value is not properly escaped and illegal in `StringValue`: https://spec.graphql.org/June2018/#StringValue

fix(store): prevent non-spec compliant schemas to breaking the build

---

.changeset/stupid-chicken-guess.md
packages/transforms/rename/src/wrapRename.ts
packages/transforms/rename/test/__snapshots__/wrapRename.spec.ts.snap
packages/transforms/rename/test/wrapRename.spec.ts

The Rename transform allows regex for types and field renaming. However it doesnt support the ability to use type and field regex for arguments renames. So If I'd wanted to rename the arguments of a bunch of types or fields, I'd have to add an argument rename for each of them.
The solution is quite simple really, it allows arguments renaming actions to support regex values for types and fields.
Additionally it fixes an issue in `wrapRename.ts:L88`, where the argument regex is being applied to the `fieldName` instead of to the argName.
```typescript
if (useRegExpForArguments) {
const argNameRegExp = new RegExp(fromArgumentName, regExpFlags);
replaceArgNameFn = (typeName, fieldName, argName) =>
typeName === toTypeName && fieldName === toFieldName
? fieldName.replace(argNameRegExp, …
```

Enhances renaming for arguments

---

.changeset/sour-tables-kick.md
examples/json-schema-subscriptions/.meshrc.yml
examples/json-schema-subscriptions/package.json
package.json
packages/config/src/process.ts
packages/config/yaml-config.graphql
packages/plugins/live-query/package.json
packages/plugins/live-query/src/index.ts
packages/plugins/live-query/yaml-config.graphql
packages/runtime/src/get-mesh.ts
packages/runtime/src/types.ts
packages/transforms/rename/src/wrapRename.ts
packages/transforms/rename/test/wrapRename.spec.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
packages/types/src/index.ts
tsconfig.json
website/docs/guides/error-handling.mdx
website/docs/guides/live-queries.mdx

Declarative Based Plugin System;
We can create Mesh specific plugins which still follow Envelop's Plugin signature like we do for Tools transforms or we can use the existing plugins like below;
```yaml
plugins:
- liveQuery: # This will load @graphql-mesh/plugin-live-query
liveQueryInvalidations:
- field: Mutation.addTodo
invalidate:
- Query.todos
- sentry: # This will load @envelop/sentry
includeRawResult: true
- graphqlJit: # This will load @envelop/graphql-jit
disableLeafSerialization: false
```
And in the future we can introduce more hooks besides Yoga's and Envelop's to control phases of Mesh. It can be kind of presets including different transforms and envelop plugins maybe???

Experiment: Mesh Declarative Plugin System

---

.changeset/serious-mugs-argue.md
examples/mysql-employees/example-query.graphql
examples/mysql-employees/tests/__snapshots__/mysql-employees.test.js.snap
packages/handlers/mysql/src/index.ts

Add relation fields other way around.
In case of insert, update and so on, respect multiple primary keys.
Instead of the following complex resolver, MySQL handler now handles those relations automatically;
```ts
import { print } from 'graphql'
import { Resolvers} from './.mesh'
export const resolvers: Resolvers = {
articles: {
article_categories: {
selectionSet: /* GraphQL */ `
{
id
}
`,
resolve: ({ id }, args, context, info) => context.relationtest.Query.article_to_categories({
args: {
where: {
article_id: id.toString(),
}
},
context,
info,
valuesFromResults: results => results.map(({ article_categories }) => article_categories).flat(),
selectionSet: selectionSetNode => /* GraphQL */`
{
article_categories {
${selectionSetNode.selections.map(selectionNode => …
```

feat(mysql): handle many-to-many relations automatically

---

.changeset/fifty-moles-work.md
packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts

Currently, the OpenApi handler concatenates array values in query params like so:
`http://myRestapi/endpoint?foo=bar,qux`
Whilst this serialization might be supported by some APIs, it is not the default behaviour for OpenApi, which is instead to generate separate parameters for each array item, like so:
`http://myRestapi/endpoint?foo=bar&foo=qux`
This PR address this issue in order to obtain separate parameters per array item as per default OpenApi behaviour.

Fix serialization of array values in query parameters

---

examples/grpc-example/start-server.js
website/docs/guides/graphql-code-generator.mdx
website/docs/recipes/as-sdk.mdx

The generated SDK should be called with `getMeshSDK` not `getMeshSdk`.
Related https://github.com/Urigo/graphql-mesh/issues/4050

Fix the typo referencing to the generated SDK in the docs

---

.changeset/eight-bats-attack.md
packages/cache/redis/src/index.ts

When having 
```
cache:
redis:
url: '{env.REDIS_DSN}'
```
it simply doesn't work because its interoplated after it's parsed, but cannot be parsed in first place because `{env.REDIS_DSN}` is not an valid url.
Please describe the …

Invalid URL at new NodeError

---

.changeset/new-flies-taste.md
packages/cli/src/config.ts
packages/handlers/json-schema/yaml-config.graphql
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/json-schema/src/types.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
website/docs/generated-markdown/JsonSchemaHandler.generated.md
website/src/pages/api/covid/json-schema-covid/example-queries/getData_step1.graphql
website/src/pages/api/covid/json-schema-covid/sources/WorldPop.yml
website/src/pages/api/covid/json-schema-covid/tests/__snapshots__/json-schema-covid.test.js.snap
website/src/pages/api/covid/json-schema-covid/tests/json-schema-covid.test.js

Closes https://github.com/Urigo/graphql-mesh/issues/4077
**New `exposeResponseMetadata `flag to expose the details of the HTTP responses received from the remote API**
```yml
responseSchema: ...
exposeResponseMetadata: true
```
Now you will have another field called `$response` in the response type;
```graphql
type MyResponseType {
myFooField: String
_response: ResponseMetadata
}
type ResponseMetadata {
url: URL
status: Int
method: String
headers: JSON
body: String
}
```

feat(json-schema): new exposeResponseMetadata flag to expose the details of the HTTP responses received from the upstream

---

.changeset/nice-countries-explode.md
packages/config/CHANGELOG.md
packages/handlers/graphql/package.json
packages/handlers/graphql/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/docs/generated-markdown/GraphQLHandlerHTTPConfiguration.generated.md
yarn.lock

**New `credentials` configuration option**
Previously it wasn't possible to configure `credentials` of outgoing `Request` object passed to `fetch`. And the default behavior was `same-origin`.
Now it is possible to configure it and you can also remove it completely for the environments (e.g. CF Workers) to avoid errors like `'credentials' hasn't been implemented yet` etc.
```yml
graphql:
endpoint: ...
credentials: disable
```

feat(graphql): new 'credentials' option to configure `RequestCredentials`

---

.changeset/rotten-walls-shop.md
.changeset/wild-kangaroos-chew.md
examples/spacex-cfw/.env
examples/spacex-cfw/.meshrc.yml
examples/spacex-cfw/package.json
examples/spacex-cfw/src/index.ts
examples/spacex-cfw/wrangler.toml
packages/cache/cfw-kv/src/index.ts
packages/cli/src/commands/serve/graphql-handler.ts
packages/config/src/process.ts
packages/config/src/utils.ts
packages/cross-helpers/browser.js
packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
packages/handlers/soap/src/index.ts
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/runtime/src/get-mesh.ts
packages/utils/src/getHeadersObj.ts
packages/utils/src/index.ts

**Improvements on string interpolation ({env.sth} or {context.headers.sth}) for different environments**
As we mention in most of our docs, we usually expect a key-value `header` object in the context.
But Fetch-like environments don't have this kind of object but instead `Headers` object which is a kind `Map`.
Now Mesh can detect this and automatically convert it to the key-value object especially for Yoga users.
Also Mesh now handles `env` in a better way for non-Node environments;
Consider `import.meta.env` as `env` if available, else take `globalThis` as `env`.

Improve string interpolation in non Node environments

---

.changeset/itchy-lemons-shake.md
packages/handlers/grpc/src/index.ts

Closes https://github.com/Urigo/graphql-mesh/issues/4113

Fix missing scalar 'File' error when there is a stream request in the gRPC protobuf schema

---

.changeset/odd-planes-think.md
.github/workflows/tests.yml
packages/utils/src/read-file-or-url.ts
packages/utils/test/read-file-or-url.spec.ts

Closes https://github.com/Urigo/graphql-mesh/issues/4094
`json-machete` uses `readFileOrUrl` from `@graphql-mesh/utils` package. Differently than the other users of this function usually provide an absolute path. But `json-machete`'s `deference` function nestedly resolves the differences with dynamic base paths. 
For example, when it resolves `../x/y/z/foo.json`, it uses `process.cwd` but then, it should resolve the `$ref: "../t/bar.json"` path with `foo.json`'s directory.
That's the case, readFileOrUrl ensures the path is absolute and resolves it correctly with the given "cwd".

fix(read-file): fix path resolution on Windows

---

.changeset/heavy-ways-talk.md
packages/handlers/thrift/src/index.ts
packages/runtime/src/get-mesh.ts
packages/store/src/index.ts

Usually there is only one error thrown and in that case we can throw it as it is instead of wrapping it inside AggregateError so it would be easier for the user to debug.

Do not use AggregateError if there is only one error

---

.changeset/many-cats-eat.md
packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts

At trainline we have a swagger schema with a bunch of loops in types ex:
```
type TypeA  {
childrens: [TypeA]
}
``` 
This was causing a `Failed to generate the schema RangeError: Maximum call stack size exceeded. I managed to track the issue to the JSON.stringify that was using the entire object. Probably due to the cycle dependencies it has some references pointing to each other which will make the JSON.stringify recursivity to never end.
Fixes # ([issue](https://github.com/Urigo/graphql-mesh/issues/4152))
Adding links to sandbox or …

fix json stringify Maximum-call-stack-size-exceeded

---

website/docs/transforms/hoist.mdx

_The PR template doesn't match this PR. This is a documentation update_
Hey!
It seems like there's a minor issue with the documentation. It has:
```yml
transforms:
- hoist:
...
```
While it should be 
```yml
transforms:
- hoist-field:
...
```

docs(hoist): update transformer name

---

.changeset/clever-zebras-switch.md
packages/config/src/process.ts
packages/mergers/bare/package.json
packages/mergers/bare/src/index.ts

Related https://github.com/graphprotocol/graph-client/issues/167

fix: do not ignore resolvers when there is a single source w/ an executor

---

.changeset/red-squids-train.md
packages/json-machete/src/compareJSONSchemas.ts
packages/json-machete/src/healJSONSchema.ts
packages/json-machete/src/referenceJSONSchema.ts
packages/json-machete/src/visitJSONSchema.ts
packages/json-machete/tests/compareJSONSchemas.test.ts
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/src/getUnionTypeComposers.ts
packages/loaders/json-schema/test/execution.test.ts
packages/loaders/json-schema/test/fixtures/book.json
packages/loaders/json-schema/test/getComposerFromSchema.test.ts
packages/loaders/json-schema/test/integration.test.ts
packages/loaders/openapi/tests/__snapshots__/docusign.test.ts.snap
packages/types/src/config-schema.json
packages/types/src/config.ts
website/src/generated-markdown/JsonSchemaHandler.generated.md
website/src/generated-markdown/JsonSchemaHandlerBundle.generated.md
website/src/generated-markdown/QueryStringOptions.generated.md

Fixes https://github.com/Urigo/graphql-mesh/issues/4211

Rewrite JSON Schema Visitor

---

.changeset/tender-walls-grin.md
packages/handlers/openapi/package.json
packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
packages/handlers/openapi/test/fixtures/nested_object.json
packages/handlers/openapi/test/nested_objects.test.ts
packages/handlers/openapi/test/nested_objects_server.ts

This closes #2911: When translating from OpenAPI calls to GraphQL, nested query objects aren't correctly set - it will only accept primitive objects, which is especially problematic when you don't control the underlying OpenAPI specification. (e.g. using a third party service).
N/A
- OS: Windows 10 running VSCode dev container: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16-bullseye
- NodeJS: 16
N/A

Fixes #2911: Nested query parameters shouldn't cause errors.

---

.changeset/json-machete-dependencies.md
.changeset/sour-cougars-relate.md
packages/json-machete/package.json
packages/json-machete/src/dereferenceObject.ts
packages/json-machete/src/healJSONSchema.ts
packages/json-machete/src/referenceJSONSchema.ts
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/src/getDereferencedJSONSchemaFromOperations.ts
packages/loaders/json-schema/src/getGraphQLSchemaFromDereferencedJSONSchema.ts
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/types/src/config-schema.json
packages/types/src/config.ts

JSON Schema loader tries to fix your JSON Schema while creating a final bundle for Mesh. Usually it works and it has a chance to have a different result rather than you expect. In the long term, if you don't fix your JSON Schema, you might get different results once the internals of `healJSONSchema` is changed.
In order to see which parts of your schema need to be fixed, you can enable the debug mode with `DEBUG=healJSONSchema` environment variable.
Now you can see which operation has which HTTP request details in the field description with the new debug mode.

Add more verbose logging for healJSONSchema and better debug details view in field descriptions

---

.changeset/yellow-laws-behave.md
packages/cli/src/commands/serve/serve.ts
packages/handlers/json-schema/CHANGELOG.md
packages/handlers/new-openapi/CHANGELOG.md
packages/loaders/json-schema/CHANGELOG.md
packages/loaders/openapi/CHANGELOG.md

Mesh server will fail with `TypeError: Cannot read properties of undefined (reading 'headers')` if WebSocket clients don't provide any `connectionParams` at this location:
https://github.com/Urigo/graphql-mesh/blob/a134d17deba62db438d68f1ee81ef4adbcf32691/packages/cli/src/commands/serve/serve.ts#L173
Start any Mesh server, connect to it using [GraphiQL with WebSockets only](https://gist.github.com/enisdenjo/a68312878fdc4df299cb0433c60c1dea).
The weirdest thing is: why are the `connectionParams` not considered optional ([because they really are](https://github.com/enisdenjo/graphql-ws/blob/1a79552690ed1d07482585327b03613571537612/src/common.ts#L101) and [here too](https://github.com/enisdenjo/graphql-ws/blob/1a79552690ed1d07482585327b03613571537612/src/server.ts#L502))?

fix(cli): WebSocket clients mustn't provide `connectionParams`

---

.changeset/young-owls-own.md
packages/cli/src/commands/serve/serve.ts

In order to correctly assemble request headers and inject the ones from WebSocket, the request must be in the Node-like `req` object for envelop context factory.
https://github.com/Urigo/graphql-mesh/blob/79ade1b7fb8b72a4185fbd06438a44ed3fb4bd36/packages/runtime/src/get-mesh.ts#L143-L157
Fixes #4040
Manually.

fix(cli): WebSocket request must be under `req` for envelop context

---

.changeset/six-parents-search.md
packages/loaders/json-schema/src/bundle.ts

When a bundle from a CDN or somewhere else is used as an input instead of locally built artifacts, `operationHeaders` from the actual configuration file was ignored.
This PR fixes this issue.

fix(json-schema): do not ignore operationHeaders defined in the config even if they are defined in the bundle

---

.changeset/six-dots-breathe.md
packages/string-interpolation/package.json

A missing licence field in the string-interpolation package.
Fixes https://github.com/Urigo/graphql-mesh/issues/4309
None

chore: add licence field (MIT) in string-interpolation package.json

---

website/src/pages/docs/transforms/federation.mdx

I hope I can skip the PR template and creating an issue for such a small change :) If not, let me know.
`external` should be nested in `config:`, not shown on the top level
See https://github.com/Urigo/graphql-mesh/blob/master/packages/transforms/federation/yaml-config.graphql#L11

docs(transforms:federation): `external` should be nested in `config:`

---

.changeset/moody-pets-retire.md
packages/cli/src/commands/ts-artifacts.ts
packages/cli/src/index.ts
packages/config/src/process.ts

fix(cli/config): deduplicate imports in the artifacts

---

.changeset/cyan-beans-bake.md
packages/transforms/naming-convention/package.json
packages/transforms/naming-convention/src/bareNamingConvention.ts
packages/transforms/naming-convention/src/index.ts
packages/transforms/naming-convention/src/shared.ts
packages/transforms/naming-convention/src/wrapNamingConvention.ts
packages/transforms/naming-convention/test/__snapshots__/bareNamingConvention.spec.ts.snap
packages/transforms/naming-convention/test/__snapshots__/wrapNamingConvention.spec.ts.snap
packages/transforms/naming-convention/test/bareNamingConvention.spec.ts
packages/transforms/naming-convention/test/wrapNamingConvention.spec.ts
packages/transforms/naming-convention/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/src/generated-markdown/NamingConventionTransformConfig.generated.md
website/src/pages/docs/transforms/naming-convention.mdx
website/src/pages/docs/transforms/transforms-introduction.mdx
yarn.lock

The naming-convention transform does not currently support bare mode; Tthis PR addresses this.
Hi added a coupe of more tests, especially around ENUMS values both in response and request (which covers #4490).
I applied all tests against "bare" and "wrap" mode.
The implementation is a bit complex, but I managed to get all the renames applied through naming-convention across types fields, input objects, and enums handled with a single resolver wrapper. This performs a decent level of logic but overall feels like a significant performance improvement compared to how many resolvers wrappers are created by the equivalent "wrap" mode.

Introduce 'bare' mode on naming-convention transform

---

.changeset/@graphql-mesh_cli-4571-dependencies.md
.changeset/@graphql-mesh_grpc-4571-dependencies.md
.changeset/@graphql-mesh_http-4571-dependencies.md
.changeset/ninety-pots-guess.md
packages/runtime/src/get-mesh.ts
packages/runtime/test/getMesh.test.ts

Fixes https://github.com/Urigo/graphql-mesh/issues/4570

fix(runtime): choose correct root type name for the source

---

.changeset/brave-toys-marry.md
packages/transforms/naming-convention/src/bareNamingConvention.ts
packages/transforms/naming-convention/test/bareNamingConvention.spec.ts
packages/transforms/naming-convention/test/wrapNamingConvention.spec.ts

This PR fixes two issue happening with `bare` naming convention transform:
1. missing arguments when the applied naming-convention resolves to the same name as the original
2. ENUM values not mapped when the ENUM is wrapped in NonNull type

Fix issues with bare naming-convention

---

packages/utils/src/logger.ts

Updated default default method parameter value to correctly only trim when `isDebug` is false.
Fixes #4609
Tested locally on my own machine
- OS: MacOS Monterey
- `@graphql-mesh/cli@0.78.25`:
- NodeJS: 16.14.0

Fix issue where logger incorrectly trimming line

---

.changeset/@graphql-mesh_graphql-4604-dependencies.md
.changeset/@graphql-mesh_merger-federation-4604-dependencies.md
.changeset/@graphql-mesh_merger-stitching-4604-dependencies.md
.changeset/@graphql-mesh_mysql-4604-dependencies.md
.changeset/@graphql-mesh_odata-4604-dependencies.md
.changeset/@graphql-mesh_postgraphile-4604-dependencies.md
.changeset/@graphql-mesh_runtime-4604-dependencies.md
.changeset/@graphql-mesh_transform-encapsulate-4604-dependencies.md
.changeset/@graphql-mesh_transform-federation-4604-dependencies.md
.changeset/@graphql-mesh_transform-filter-schema-4604-dependencies.md
.changeset/@graphql-mesh_transform-hoist-field-4604-dependencies.md
.changeset/@graphql-mesh_transform-naming-convention-4604-dependencies.md
.changeset/@graphql-mesh_transform-prefix-4604-dependencies.md
.changeset/@graphql-mesh_transform-rename-4604-dependencies.md
.changeset/@graphql-mesh_transform-type-merging-4604-dependencies.md
.changeset/@graphql-mesh_types-4604-dependencies.md
.changeset/@graphql-mesh_utils-4604-dependencies.md
examples/neo4j-example/tests/__snapshots__/neo4j-example.test.js.snap
website/next.config.mjs
website/src/pages/docs/cache/cache-introduction.mdx
website/src/pages/docs/cache/meta.json
website/src/pages/docs/config-reference.mdx
website/src/pages/docs/handlers/openapi.mdx
website/src/pages/docs/meta.json

Create Mesh config dedicated document

Config doc

---

examples/openapi-stackexchange/list-questions.query.graphql
examples/openapi-stackexchange/test/__snapshots__/openapi-stackexchange.test.ts.snap
examples/openapi-stackexchange/test/openapi-stackexchange.test.ts

openapi-stackexchange example does not seem to build (`mesh build`) due to updated fields from StackExchange  
- 
I updated the fields and can confirm that `mesh build` was successful
- OS: Mac OS
-  `@graphql-mesh/cli: "0.78.25"`
- `@graphql-mesh/openapi": "0.33.20"`
- NodeJS: v16 LTS
- [] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
This is a relatively small change that's why I haven't created an issue. Hope that's alright.

Update query fields for openapi-stackexchange example

---

.changeset/real-baboons-provide.md
packages/cli/src/commands/serve/serve.ts

Browsers cannot open `0.0.0.0` because this address means _all_ network interfaces. Instead, even if serving is bound to `0.0.0.0` the browser should open `localhost`.

Replace `0.0.0.0` with `localhost` while opening in browser

---

.changeset/smooth-files-hear.md
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/openapi/tests/explode.test.ts
packages/loaders/openapi/tests/fixtures/explode.yml

This PR fixes a regression in the query string logic in the `json-schema` loader so that `explode: true` in the `openapi` loader works properly for `type: string` parameters.
Fixes https://github.com/Urigo/graphql-mesh/issues/4677.
N/A
This PR updates `explode.test.ts` to include new test cases for `object` and `string` parameters.
See https://github.com/Urigo/graphql-mesh/issues/4677 for reproduction steps.
- OS: MacOS
- `@graphql-mesh/openapi`: `^0.33.26`
- NodeJS: 16.17.1
N/A

fix(json-schema): restore support for `explode: true` with strings

---

.changeset/tasty-apes-leave.md
packages/transforms/naming-convention/src/bareNamingConvention.ts
packages/transforms/naming-convention/test/bareNamingConvention.spec.ts
packages/transforms/naming-convention/test/wrapNamingConvention.spec.ts

This PR introduces proper support to type pointers on `bare` implementation of naming-convention transform.
More specifically GraphQLList types were not supported when renaming the output value.
To support this scenario a new function to detect the underlying type has been introduced.
Also, the resolver implementation is now able to loop through resolver values to rename those.
I have introduced new tests to check these more complex scenarios, both in `bare` and `wrap` modes.

Add support for type pointers to bare naming convention transform

---

packages/mergers/stitching/src/index.ts

When a federation schema is converted to stitching `schema.extensions` is lost.
- I've verified that extensions in schemas are present in a global schema transform.
- OS: macOS
- `@graphql-mesh/...`: master
- …

Carry over schema extensions in replaceFederationSDLWithStitchingSDL

---

.changeset/metal-seahorses-drum.md
packages/transforms/naming-convention/src/bareNamingConvention.ts
packages/transforms/naming-convention/test/__snapshots__/bareNamingConvention.spec.ts.snap
packages/transforms/naming-convention/test/__snapshots__/wrapNamingConvention.spec.ts.snap
packages/transforms/naming-convention/test/bareNamingConvention.spec.ts
packages/transforms/naming-convention/test/wrapNamingConvention.spec.ts

As per the title, this PR adds handling of AbstractTypes renames to naming convention transform, `bare` mode.
Tests for the use case have been added to both, the `bare` and `wrap` implementation

Handle AbstractTypes in "bare" mode of NamingConvention transform

---

.changeset/long-carpets-judge.md
packages/transforms/prefix/package.json
packages/transforms/prefix/src/barePrefix.ts
packages/transforms/prefix/test/barePrefix.spec.ts
packages/transforms/prefix/test/wrapPrefix.spec.ts
packages/transforms/rename/src/bareRename.ts
packages/transforms/rename/test/__snapshots__/wrapRename.spec.ts.snap
packages/transforms/rename/test/bareRename.spec.ts
packages/transforms/rename/test/wrapRename.spec.ts

This PR addresses the following points:
1. Handling of AbstractTypes renames to Rename transform in `bare` mode
2. Add support for async `resolveType` to AbstractTypes in Prefix, `bare` mode
I have added test to both `bare` and `wrap` modes of Rename transform.

Bare abstract

---

.changeset/giant-dolls-fry.md
packages/string-interpolation/package.json

This PR adds a missing `tslib` dependency to `@graphql-mesh/string-interpolation`
Fixes https://github.com/Urigo/graphql-mesh/issues/4998
N/A
N/A
N/A
N/A

fix(deps): add missing `tslib` dependency to `@graphql-mesh/string-interpolation`

---

.changeset/quiet-clouds-battle.md
packages/cli/src/commands/ts-artifacts.ts

Enhance ESM/CJS distinction on artifacts generation:
use root dir instead of `baseDir` which points to the config file folder

Use root dir for fetching tsconfig file

---

website/src/pages/docs/plugins/plugins-introduction.mdx

Updated documentation page [Plugins inroduction, chapter Mesh specific plugin hooks](https://the-guild.dev/graphql/mesh/docs/plugins/plugins-introduction#mesh-specific-plugin-hooks).
- Added dummy implementation with import and types
- Added link to native Envelop plugins
Fixes #5013
Markdown change

Improve docs page Plugin introduction

---

website/src/pages/docs/guides/_meta.json
website/src/pages/docs/guides/dynamic-vars.mdx

Dynamic variables document

---

.changeset/cold-jobs-walk.md
packages/cross-helpers/package.json
packages/json-machete/package.json

This PR adds missing `graphql` peer dependencies to `@graphql-mesh/cross-helpers` and `json-machete`, which will resolve peer dependency warnings on install, e.g.:
```txt
➤ YN0002: │ @graphql-mesh/cross-helpers@npm:0.2.6 doesn't provide graphql (p306b4), requested by @graphql-tools/utils
➤ YN0002: │ json-machete@npm:0.15.9 doesn't provide graphql (p9f76e), requested by @graphql-tools/utils
```
This relates to https://github.com/Urigo/graphql-mesh/issues/2923, although that issue is old and may not be fully resolved by this.
N/A
N/A

fix(deps): add missing graphql peer deps

---

.changeset/quiet-icons-poke.md
packages/plugins/prometheus/src/index.ts
packages/plugins/prometheus/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts

Issue: [5144](https://github.com/Urigo/graphql-mesh/issues/5144)
Attempt to add additional flags for controlling the labels of metrics emitted by graphql mesh, specifically to remove any request/response headers, as these are very poor choices for metric labels, as the cause a cardinality explosion as each metric ends up being unique. 
note: I am not a node/javascript/typescript developer, so this may require additional eyes. 
Fixes # (5144)
expected)
- [x ] My changes generate no new warnings

Add additional configuration to disable including req/resp header labels

---

packages/handlers/grpc/src/index.ts

Propagate load options from the mesh config to the gRPC handler
Fixes #5277
Tested manually
- OS: macOS Ventura 13.2.1
-  Package versions
```
"@graphql-mesh/cli": "^0.82.23",
"@graphql-mesh/graphql": "^0.34.6",
```
- NodeJS: v18.14.1

propagate load options from the config to the gRPC handler

---

packages/loaders/json-schema/src/directives.ts
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/src/getTypeResolverFromOutputTCs.ts
packages/loaders/openapi/package.json
packages/loaders/openapi/tests/__snapshots__/discriminator.test.ts.snap
packages/loaders/openapi/tests/discriminator.test.ts
packages/loaders/openapi/tests/fixtures/discriminator-mapping.yml
packages/loaders/openapi/tests/schemas.test.ts

If discriminator mapping has a different name, `getTypeResolverFromOutputTCs` fails to resolve it to the correct schema. This PR adds a DiscriminatorMappingDirective and tags discriminated unions with its mappings if theyre existent.
Fixes # TODO
expected)
I've added a schema that should break if you try to query for DifferentDog. Id like to add a test case for `getTypeResolverFromOutputTCs` picking the values for …

enhance(json-schema): handle discriminator mapping

---

.changeset/rich-cats-study.md
packages/loaders/json-schema/src/directives.ts
packages/loaders/json-schema/src/getTypeResolverFromOutputTCs.ts
packages/loaders/json-schema/src/getUnionTypeComposers.ts
packages/loaders/openapi/tests/__snapshots__/basket.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/calendly.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/cloudflare.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/discriminator.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/example_api.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/example_api4.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/example_api6.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/government_social_work.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/nested_objects.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/oneof-without-descriminator.test.ts.snap
packages/loaders/openapi/tests/fixtures/one-of-no-discriminator.yml
packages/loaders/openapi/tests/multiple-responses-swagger.test.ts
packages/loaders/openapi/tests/oneof-without-descriminator.test.ts

Union one of issue

---

.changeset/stupid-planes-reply.md
packages/loaders/soap/src/executor.ts
packages/loaders/soap/test/__snapshots__/soap.test.ts.snap
packages/loaders/soap/test/fixtures/greeting.wsdl
packages/loaders/soap/test/soap.test.ts

When schema generated from service wsdl file contains only mutations we could not create rootValue for the executor cause  `Query.placeholder` field does not contains `@soap` directive
expected)
- OS:
- …

soap: fix creating root value when only mutations present

---

packages/mergers/stitching/package.json
yarn.lock

Fix install with pnpm by updating @graphql-tools/stitch to 8.7.50. 
Sorry to not have created an issue. But you'll find an explanation in
- PR: https://github.com/ardatan/graphql-tools/pull/5235
- Issue: https://github.com/ardatan/graphql-tools/issues/5234
Since it has been integrated in the 8.7.50 version https://github.com/ardatan/graphql-tools/releases/tag/release-1683799570488 
With pnpm 8.5.0, from https://github.com/belgattitude/compare-package-managers/actions/runs/4845333008/jobs/8634183484?pr=14
- PR: https://github.com/ardatan/graphql-tools/pull/5235

chore(deps): @graphql-tools/stitch / fix pnpm installs

---

.changeset/metal-lamps-shake.md
packages/transforms/rename/src/wrapRename.ts
packages/transforms/rename/test/wrapRename.spec.ts
packages/transforms/rename/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/src/generated-markdown/RenameTransform.generated.md
website/src/generated-markdown/RenameTransformObject.generated.md

The rename transform uses an ignore list by default to skip renaming certain types (e.g.: scalars). This could cause potential collisions if more than one schema defines the same scalars, since those cannot be renamed to avoid the mentioned collisions.
A flag was added to the rename transform configuration, which is true by default so as to keep backwards compatibility, which allows to toggle the usage of the ignore list.
Fixes #5341
action on …

Rename transform toggle ignore list

---

.changeset/eighty-islands-dress.md
packages/loaders/json-schema/src/addRootFieldResolver.ts
packages/loaders/openapi/tests/oneof-without-descriminator.test.ts

When you have an enum in the open api
```graphql
enum A_const @typescript(type: "\"A\"") @example(value: "\"A\"") {
A @enum(value: "\"A\"")
}
```
When it is used in the input
```graphql
input TestType_Input {
A_const: A_const
}
```
It will be serialized as
```json
A
```
which is an invalid json
While correct json string should be quoted
```json
"A"
```
expected)
Please describe the tests that you ran to verify your …

fix: OpenApi enums serialization

---

.changeset/many-comics-beg.md
packages/utils/src/resolve-additional-resolvers.ts

Allows to use nested objects in the `sourceArgs` argument of `additionalResolvers` or `@resolveTo` directive.
Fixes #5729 
Tested using the example getting started repo.

handle nested object in sourceArgs map

---

packages/cli/src/commands/serve/serve.ts

Fixes #5778
I believe this is a one-line fix for forking when running in a production environment.
Fixes #5778 
n/a
Tested with `mesh dev` (no forking) and `mesh start` (8 forks) locally.
- OS: Linux
- `@graphql-mesh/...`: 0.86.0
- NodeJS: v18.16.1
If this is a relatively large or complex change, kick off the discussion by explaining why you chose
the solution you did and what alternatives you …

Fix to fork if and only if in production

---

.changeset/giant-jars-bake.md
.changeset/new-geese-allow.md
.changeset/nice-paws-protect.md
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/test/getComposerFromSchema.test.ts
packages/loaders/openapi/tests/__snapshots__/cloudflare.test.ts.snap

Fixes #5641
[Code Sandbox](https://codesandbox.io/p/github/cweckesser/graphql-mesh-testing/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A …

fix: Allow deep merging objects in allOf operations

---

.changeset/tasty-maps-know.md
packages/handlers/mysql/src/index.ts
packages/handlers/mysql/src/mysql.d.ts

The MySQL handler was marking auto-incremented columns as required fields in the GraphQL schema.
It's wrong since you can provide `NULL` or omit auto-incremented fields even if they are marked as `NOT NULL`.
It was also marking as required fields `NOT NULL` columns with defined default, which is wrong for the same reason.
Fixes #5350
Fixes #2182

fix auto-incremented columns marked as required fields

---

.changeset/@graphql-mesh_transform-encapsulate-5886-fix-applyto.md
packages/transforms/encapsulate/src/index.ts
packages/transforms/encapsulate/test/encapsulate.spec.ts

Respects the applyTo option in GraphQL Mesh encapsulate transform
Fixes #5885
If this is a relatively large or complex change, kick off the discussion by explaining why you chose
the solution you did and what alternatives you considered, etc...

fix: respect settings in applyTo config(#5885)

---

.changeset/thin-pears-beam.md
packages/cache/redis/src/index.ts
packages/cache/redis/test/cache.spec.ts
packages/cache/redis/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/src/generated-markdown/RedisConfig.generated.md

feat(redis): make lazyConnect optional in cache-redis plugin

---

.changeset/fuzzy-socks-smoke.md
packages/cache/redis/src/index.ts
packages/cache/redis/test/cache.spec.ts

Fixes #5962 
I adopted existing tests and add 1 new test for the cache-redis package.
- OS:
- NodeJS:
If this is a …

Fix: avoid set lazyConnect in case it's false for cache-redis package

---

packages/string-interpolation/src/interpolator.js
packages/string-interpolation/tests/parse-interpolation-strings.test.ts

if dataToReplace is false or 0, it will get ignored otherwise
Fixes #5817
reproduce. Please also list any relevant details for your …

fix: make applyRule() handly falsy replacements correctly

---

.changeset/cuddly-spoons-confess.md
examples/grpc-example/tests/__snapshots__/grpc.test.ts.snap
packages/handlers/grpc/src/index.ts
packages/handlers/grpc/src/utils.ts
packages/handlers/grpc/test/__snapshots__/handler.spec.ts.snap
packages/handlers/grpc/test/fixtures/proto-tests/input_bug_5880.proto
packages/handlers/grpc/test/handler.spec.ts

GRPC allows to nest message type definition. Since GraphQL doesn't have this possibility, Mesh generate schema wide uniq names for nested types by joining parent types names with an `_` character. This leads to a conflict with the way input types are generated by adding `_Input` when a nested message is named `Input`.
One way to solve this ambiguity is to replace to have to different seperators for nested type names and for input type names.
This PR replaces the joining character for nested types from `_` to `__`.
I've chosen to modify the nested type names generation since I think it will probably have less impact than modifying the inputs name generation. Not every type or schemas are using nesting feature while every schema will need input types.
Fixes #5880 
expected)
> Type names …

fix grpc handler for nested messages with name 'Input'

---

.changeset/tame-files-brake.md
packages/loaders/json-schema/src/addRootFieldResolver.ts
packages/loaders/openapi/tests/empty-response.test.ts
packages/loaders/openapi/tests/fixtures/empty-response.yml

Certain APIs will return empty responses together with 200 errors. This works correctly in grapql-mesh if there is only a 200 response defined. When there are other (error) responses defined with a schema these requests will throw an `Unexpected response` error.
This PR makes the root field resolver more forgiving and will return an an empty object, just like 204 responses are handled.
Fixes
https://github.com/wundergraph/wundergraph/issues/1196
expected)
Adding links to sandbox or providing screenshots can help us understand more about this …

fix: support empty responses with 200 status

---

packages/plugins/hive/src/index.ts

Allows that self hosting endpoint variables can be taken from env vars like nearly all other variables as well.
Fixes #6370 
Allows to source hosting information from env vars.
N/A
- OS:
- NodeJS:
None

feat: allow self hosting endpoints from env vars

---

website/src/pages/docs/guides/dynamic-vars.mdx

Add double quote to docs to prevent parsing as object literal when copying from docs
` Mesh - Supergraph Failed to generate the schema TypeError: str.match is not a function
at Interpolator.parseRules`

Add double quote to prevent parsing as object literal

---

website/src/pages/docs/handlers/openapi.mdx

Fix the code snippet in the documentation to demonstrate how one can create a customised fetch function.
The current documentation misses `function` keyword, it doesn't have the same signature as the original type `MeshFetch` and it passes a non-existing `args` variable to the `fetch` function.

Fix openapi.mdx fetch example

---

.changeset/mean-laws-thank.md
packages/transforms/rename/src/bareRename.ts
packages/transforms/rename/test/bareRename.spec.ts
packages/transforms/rename/test/wrapRename.spec.ts

This pull request solves  issue #6399 that caused that only one rename rule has been successfully applied to the target when using mode 'bare', although more rules for the target field / type were given. 
In addition to the bug fix, the pull request contains new unit tests to verify the expected behaviour for 'bare' and 'wrap' mode. 
Fixes #6399 
expected)
The bug fix has been tested by executing existing unit tests and adding new test cases for the given issue.
- OS: macOS 14.0
- `@graphql-mesh/transform-rename`: 0.96.2
- NodeJS: v18.18.0

[Rename Transformer]: Allow multiple rules for the same target when using mode 'bare'

---

.changeset/good-suits-check.md
packages/transforms/rename/src/bareRename.ts
packages/transforms/rename/test/rename.spec.ts

This change fixes a bug where scalar types could not be renamed when using 'bare' mode
Fixes #6410 
- OS: macOS 14.0
- `@graphql-mesh/transform-rename`: 0.96.2
- NodeJS: v18.18

fix(transformer/rename): Scalar types can now be renamed when using 'bare' mode

---

.changeset/good-actors-live.md
packages/transforms/naming-convention/src/bareNamingConvention.ts
packages/transforms/naming-convention/test/naming-convention.spec.ts

This pull request fixes an bug, that led to resolving issues of fields that uses arguments, when the argument name was not changed after applying the naming convention. 
Fixes #6416 
- OS: macOS 14.0
- `@graphql-mesh/transform-naming-convention`: 0.96.2
- NodeJS: v18.18.0

fix(transformer/naming-convention): Resolve unchanged arguments correctly

---

.changeset/@graphql-mesh_serve-cli-6552-dependencies.md
.changeset/clever-trees-sleep.md
packages/serve-cli/package.json

Added dependencies that are necessary to run serve-cli. Otherwise, the user has to manually install all of them one by one because the "missing dep" error happens only when running the CLI. Also goes against the documentation where you need to just install the CLI and you're off.

Include necessary dependencies

---

.changeset/stale-rocks-hammer.md
packages/serve-cli/src/runServeCLI.ts

Logging at error level (and the error itself) is a bit too much for an optional feature.

Hot reloading is optional and therefore just a warning

---

.changeset/weak-comics-shop.md
packages/serve-cli/src/bin.ts

I don't think its necessary to type-check the config. Type-checking is the responsibility of the user.
Also, helps with DX while prototyping/debugging.
Bonus points: **much** faster startup.

Transpile only mesh config

---

.changeset/olive-papayas-remain.md
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/test/getComposerFromSchema.test.ts
packages/loaders/openapi/tests/__snapshots__/calendly.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/looker.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/spotify.test.ts.snap
packages/transports/rest/src/directives/process.ts
packages/transports/rest/src/directives/scalars.ts
packages/transports/rest/src/directives/utils.ts
packages/transports/rest/src/index.ts

Closes https://github.com/ardatan/graphql-mesh/pull/6561
Fixes #6560

fix(json-schema): handle nullable required props as nullable fields in GraphQL

---

.changeset/nasty-peas-worry.md
packages/handlers/mongoose/src/index.ts

Add string interpolation on connectionString config value when connecting to mongo for the mongoose handler. On local development one might connect to the localhost but in staging or production, the environment variables should be available to select a different connection string. Also the connection string sometimes has credentials included and this should not be submitted to source code.
Related to Issue # 5296 (which seems to be already fixed)
N/A
N/A
N/A
[CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/maste …

Add string interpolator for mongoose handler config: connectionString

---

.changeset/flat-trains-smile.md
.changeset/thirty-balloons-cheat.md
packages/cli/src/config.ts
website/src/pages/docs/cli-commands.mdx

A missing argument to `validateConfig()` in `packages/cli/src/config.ts` is preventing the user-provided `--throwOnInvalidConfig` flag from taking effect.
Fixes https://github.com/ardatan/graphql-mesh/issues/6571
Please describe the tests that …

mesh build --throwOnInvalidConfig does not throw on invalid config

---

.changeset/stupid-plums-fail.md
packages/fusion/runtime/src/index.ts

Because why not? And there'll be need to change the subgraph URL during runtime (or any other transport features).
Also, there's just one `transportKind` argument in the `onSubgraphExecute` instead of its spread.

Change executionRequest in onSubgraphExecute hook and use one transportKind argument instead of spreading it

---

website/src/pages/docs/plugins/max-tokens.mdx

Fixing typo in docu. The config param name was wrong.

fix typo in docu

---

.changeset/spotty-chefs-collect.md
packages/legacy/runtime/src/utils.ts
packages/legacy/runtime/test/isGraphQLJitCompatible.test.ts

GraphQL JIT should be disabled in case of nested input types
Workaround for https://github.com/zalando-incubator/graphql-jit/issues/81

fix(runtime): disable GraphQL JIT if there are nested input types

---

packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/types.ts

Yoga by default displays a landing page on the root path `/`. This can be disabled in yoga options, but the options was not added to mesh config.

allow to configure the yoga landing page display

---

.changeset/few-teachers-do.md
examples/json-schema-covid/tests/__snapshots__/json-schema-covid.test.ts.snap
packages/legacy/runtime/src/get-mesh.ts
packages/legacy/runtime/test/getMesh.test.ts

This makes generated schema deterministic, as it will always be ordered in the same way as the schemas passed to .meshrc.
Fixes #6947 
expected)
Previously:
https://github.com/ardatan/graphql-mesh/assets/5903616/8238c75d-9935-4874-8bd1-b729ce78b163
After
https://github.com/ardatan/graphql-mesh/assets/5903616/4950a55a-c2d4-4f7d-ad79-fd796635f9da
- OS: MacOS
- `@graphql-mesh/...`: runtime
- NodeJS: 21.x
I don't think this is a breaking change - using index in this way will generate a consistent result. If one of the schema generation fails, the …

Make schema generation consistent

---

.changeset/tidy-seahorses-bake.md
packages/plugins/response-cache/src/index.ts

Conntext not available when evaluating responseCache if function. Reason is that javascript function constructor does not inherit lexical scope. Instead we must pass the context as a named arg.
Fixes #6925 
expected)
- OS:
- …

fix context undefined in useResponseCache ifDef enabled fn

---

.changeset/afraid-dancers-nail.md
.changeset/proud-spoons-matter.md
.changeset/shy-snakes-swim.md
packages/loaders/soap/src/SOAPLoader.ts
packages/loaders/soap/test/__snapshots__/examples.test.ts.snap
packages/loaders/soap/test/examples.test.ts
packages/loaders/soap/test/fixtures/axis.wsdl

- Support documents without any prefixes on W3 definitions like `xsd` etc
WSDL definitions might not have any prefix for W3 definitions as in here;
```xml
<xs:schema />
```
Unlike this one;
```xml
<schema />
```
Both are supported, previously it was throwing while looking for a namespace prefix for W3. Now it considers W3 to be the default/global namespace if there is no explicit prefix for it in the document.
```xml
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
```
- Support new numeric types; `integer`, `negativeInteger`, `nonNegativeInteger`, `nonPositiveInteger` and `positiveInteger`
See all the numeric types in SOAP;
https://www.w3schools.com/xml/schema_dtypes_numeric.asp
- Support extended enum types, before it was supporting `string` only but it might be other …

SOAP: Support more numeric types, handle enums better and support nonprefixed namespaces

---

.changeset/late-ghosts-turn.md
packages/plugins/hive/src/index.ts
packages/plugins/hive/tests/hive.test.ts

This PR disables `autoDispose` option in `createHiveClient` call inside Hive plugin, so Hive client can only be destroyed with Mesh's `destroy` event.

fix(hive): disable `autoDispose`

---

.changeset/orange-seas-knock.md
packages/legacy/config/src/utils.ts
packages/legacy/config/yaml-config.graphql
packages/legacy/types/src/config-schema.json
packages/legacy/types/src/config.ts

The `logger` option was always meant as a path to a file exporting a logger instance not as the logger instance itself - it has to be this way so that code generation works and can correctly load the logger.
I've changed the documentation and typing of the `logger` option, as well as fixing the import path similarly to how other imports work (like `additionalEnvelopPlugins`).
Fixes #7107 
I've built the library and used the built artifacts in my project with success - I'd appreciate hints on how to test this better.
- OS: macOS 14.5
- `@graphql-mesh/cli`: v0.90.4
- NodeJS: v18.12.1
changeset using …

Fix generating logger import code and improve documentation

---

.changeset/@graphql-mesh_supergraph-7149-dependencies.md
.changeset/forty-tools-shout.md
packages/legacy/handlers/supergraph/package.json
packages/legacy/handlers/supergraph/src/index.ts
packages/legacy/handlers/supergraph/tests/fixtures/service-author/typeDefs.graphql
packages/legacy/handlers/supergraph/tests/fixtures/service-book/resolvers.ts
packages/legacy/handlers/supergraph/tests/fixtures/service-book/typeDefs.graphql
packages/legacy/handlers/supergraph/tests/fixtures/supergraph.graphql
packages/legacy/handlers/supergraph/tests/supergraph.spec.ts
yarn.lock

Fix the support for WebSockets configuration for supergraph handler
For example;
```yaml filename="mesh.config.yaml"
sources:
- name: MySupergraph
handler:
supergraph:
source: # ...
subgraphs:
- name: MySubgraph
subscriptionsEndpoint: ws://localhost:4000/graphql
subscriptionsProtocol: WS
```

fix(supergraph): support WebSockets subscriptions protocol for subgraphs

---

.changeset/moody-cameras-hunt.md
packages/legacy/utils/src/logger.ts
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/types.ts

This creates the logger with `LogLevel` during `createServeRuntime` so it is available in `plugins` factory function.
This fixes the bug of missing `logger` in the plugin context.

fix(serve-runtime): construct logger during init

---

.changeset/fifty-ears-camp.md
packages/serve-cli/src/run.ts
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/types.ts
packages/serve-runtime/tests/__snapshots__/serve-runtime.spec.ts.snap
packages/serve-runtime/tests/serve-runtime.spec.ts
packages/serve-runtime/tests/supergraph.graphql
yarn.lock

Change the default behavior of Serve Runtime;
If no `supergraph` or `hive` or `proxy` is provided
- If `HIVE_CDN_ENDPOINT` and `HIVE_CDN_TOKEN` are provided, use them to fetch the supergraph from the Hive CDN
- If not, check for a local supergraph file at `./supergraph.graphql`

feat(serve-runtime): better defaults

---

.changeset/@graphql-mesh_fusion-runtime-7183-dependencies.md
.changeset/@graphql-mesh_http-7183-dependencies.md
.changeset/@graphql-mesh_plugin-response-cache-7183-dependencies.md
.changeset/@graphql-mesh_serve-runtime-7183-dependencies.md
.changeset/flat-actors-heal.md
e2e/auto-type-merging/package.json
e2e/type-merging-batching/package.json
examples/graphql-file-upload-example/package.json
examples/v1-next/hive-example/my-graphql/package.json
packages/fusion/runtime/package.json
packages/legacy/cli/src/commands/serve/yaml-config.graphql
packages/legacy/http/package.json
packages/legacy/http/src/graphqlHandler.ts
packages/legacy/http/src/index.ts
packages/legacy/http/test/http.spec.ts
packages/legacy/types/src/config-schema.json
packages/legacy/types/src/config.ts
packages/loaders/openapi/package.json
packages/plugins/newrelic/package.json
packages/plugins/response-cache/package.json
packages/serve-runtime/package.json
website/src/generated-markdown/ServeConfig.generated.md
yarn.lock

By default, Mesh does not allow extra parameters in the request body other than `query`, `operationName`, `extensions`, and `variables`, then throws 400 HTTP Error.
This change adds a new option called `extraParamNames` to allow extra parameters in the request body.
```yaml
serve:
extraParamNames:
- extraParam1
- extraParam2
```
```ts
const res = await fetch('/graphql', {
method: 'POST',
headers: {
'Content-Type': 'application/json',
},
body: JSON.stringify({
query: 'query { __typename }',
extraParam1: 'value1',
extraParam2: 'value2',
}),
});
console.assert(res.status === 200);
```

feat(serve/legacy/http): allow extra params in body

---

.changeset/moody-coins-hug.md
packages/legacy/handlers/grpc/src/index.ts

Fixes #7174 
https://stackblitz.com/edit/github-acjw4e-rs3wnu?file=.meshrc.yml
`mesh start` failed locally then passed with a patch identical to this fix. Issue was 
- OS: MacOS
- `@graphql-mesh/grpc`: 0.100.0
- NodeJS: 16 and 20
style guidelines of this …

Lazy-initialize type._valueLookup in grpc handler

---

.changeset/blue-bottles-beam.md
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/types.ts
packages/serve-runtime/tests/serve-runtime.spec.ts
packages/serve-runtime/tests/useForwardHeaders.spec.ts

Disable validation of the operations on the gateway while using Mesh Server as a proxy
```ts filename="mesh.config.ts"
import { defineConfig as defineServeConfig } from '@graphql-mesh/serve-cli'
export default defineServeConfig({
proxy: {
endpoint: 'https://my-service.com/graphql',
},
skipValidation: true
})
```
This will disable the validation of the operations, and send the operations directly to the upstream service.

feat(serve-runtime): `skipValidation` option to skip validation while proxying

---

.changeset/nice-kangaroos-laugh.md
packages/fusion/runtime/src/unifiedGraphManager.ts
packages/fusion/runtime/src/utils.ts
packages/fusion/runtime/tests/polling.test.ts
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/getProxyExecutor.ts
packages/serve-runtime/tests/__snapshots__/serve-runtime.spec.ts.snap
packages/serve-runtime/tests/serve-runtime.spec.ts

Cleanup created transport executors per schema change
Previously they were cleaned up only on server close, which could lead to memory leaks in case of schema changes.
This PR also terminates downstream subscriptions in case of a supergraph update.

[v1] fix(runtime): cleanup transport executors per schema change

---

.changeset/few-rats-compare.md
packages/fusion/runtime/tests/polling.test.ts
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/useChangingSchema.ts

The `useChangingSchema` has also optimizations over Yoga's default `useSchema`, including:
- no `schemaByRequest` weakmap
- no setting schema on each request
- no unnecessary `onSchemaChange` invokations

[v1] Invoke `onSchemaChange` plugin hook as soon as supergraph changes

---

.changeset/small-planets-push.md
packages/fusion/runtime/tests/polling.test.ts
packages/serve-runtime/package.json
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/useCompleteSubscriptionsOnSchemaChange.ts
packages/serve-runtime/src/useCompleteSubscriptionsOnUnifiedGraphDispose.ts
packages/serve-runtime/tests/__snapshots__/serve-runtime.spec.ts.snap
packages/serve-runtime/tests/serve-runtime.spec.ts
packages/serve-runtime/tests/subscriptions.test.ts
yarn.lock

Close subscriptions on disposal and schema change with different codes.
When the server gets disposed (on shutdown), all active subscriptions will complete emitting the following execution error:
```json
{
"errors": [
{
"extensions": {
"code": "SHUTTING_DOWN",
},
"message": "subscription has been closed because the server is shutting down",
},
],
}
```
However, when the server detects a schema change, all active subscriptions will complete emitting the following execution error:
```json
{
"errors": [
{
"extensions": {
"code": "SUBSCRIPTION_SCHEMA_RELOAD",
},
"message": "subscription has been closed due to a schema reload",
},
],
}
```

[v1] close subscriptions on disposal and schema change with different codes

---

website/src/pages/docs/getting-started/deploy-mesh-gateway.mdx
website/src/pages/v1/serve/deployment/node-frameworks/_meta.ts
website/src/pages/v1/serve/deployment/node-frameworks/sveltekit.mdx

Closes #7130
Note that v0 SvelteKit example straight up does not work. I spent a chunk of time debugging and decided it wasnt worth the time. [So I just removed the SK example in v0](https://github.com/ardatan/graphql-mesh/pull/7263/commits/48c1c072980173602ab686a650cd8a9e7c465a1e) and expect users to use v1.

[v1] docs(deployment): SvelteKit integration

---

.changeset/loud-teachers-hide.md
packages/compose-cli/src/loadGraphQLHTTPSubgraph.ts
packages/compose-cli/src/types.ts
packages/compose-cli/tests/loadGraphQLHTTPSubgraph.test.ts

Adds the headers specified in `schemaHeaders` to introspection queries as well as the current schema fetch requests.
Fixes #7233
Not sure which one this would qualify as
- OS: Amazon Linux
- `@graphql-mesh/runtime-serve`: latest
- NodeJS: 20
I can't run the tests on either of my machines due to half the tests failing because of `jest` and `__dirname` being undefined

[v1] Add `schemaHeaders` to introspection queries

---

.changeset/mighty-suits-pay.md
packages/legacy/handlers/odata/src/index.ts
packages/legacy/handlers/odata/test/__snapshots__/handler.spec.ts.snap
packages/legacy/handlers/odata/test/fixtures/alice.json
packages/legacy/handlers/odata/test/fixtures/bound-action.xml
packages/legacy/handlers/odata/test/handler.spec.ts

Previously OData handler failed on schemas where an action was bound to an entity set instead of one of the action's parameters. This is however [specified](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_EntitySetPath) used in the wild in Abacus OData schema (see linked issue).
Fixes #6984
`yarn test odata`
- OS: MacOS
- `@graphql-mesh/odata`: master
- NodeJS: v20
The change is not big, mostly refactoring of the `handleBoundAction` function. I would appreciate if someone familiar with OData could review my test expectations as well.

[OData] Fix action bound to entity set

---

packages/serve-cli/Dockerfile
packages/serve-cli/rollup.config.js
website/src/pages/v1/serve/deployment/docker.mdx

By moving the bundled `node_modules` outside the workdir of mesh-serve (in the root `/node_module`) we allow for easier extending of the image where copying an external `package.json` (wont overwrite an existing one in the image). We also make sure that no package manager manipulates the bundle (running `npm i` will remove the bundle modules from workdir's `node_modules`).

feat(serve-cli): isolate bundle modules in the docker image and read-only bundle files

---

.changeset/olive-waves-reflect.md
.eslintrc.json
packages/serve-cli/src/nodeHttp.ts
packages/serve-cli/src/run.ts
packages/serve-cli/src/types.ts
packages/serve-cli/src/uWebSockets.ts
website/src/pages/v1/compose/source-handlers/index.mdx
website/src/pages/v1/serve/references/config.mdx

Ability to configure max header size if you get 431 with headers payload longer than 16kb.
By default, it is 16KB. If longer headers are sent, the server will respond with a 431 status code.
```ts filename="mesh.config.ts"
import { defineConfig } from '@graphql-mesh/serve-cli'
export const serveConfig = defineConfig({
maxHeaderSize: 32 * 1024 // 32KB
})
```

feat(serve-cli): configure `maxHeaderSize`

---

.changeset/@graphql-mesh_cli-7360-dependencies.md
.changeset/@graphql-mesh_utils-7360-dependencies.md
.changeset/two-geese-relate.md
.changeset/young-tips-bake.md
packages/legacy/cli/package.json
packages/legacy/cli/src/config.ts
packages/legacy/cli/src/defaultImportFn.ts
packages/legacy/cli/src/index.ts
packages/legacy/utils/package.json
packages/legacy/utils/src/defaultImportFn.ts
yarn.lock

Closes #7342
Utils need to be kept JS env agnostic.

fix(legacy/utils,legacy/cli): no jiti in utils, but use it as default JS importer in cli

---

packages/legacy/http/test/http.spec.ts
packages/legacy/runtime/src/types.ts
packages/loaders/soap/test/soap.test.ts
yarn.lock

Compatibility tests for `useContentEncoding` plugin and legacy Mesh HTTP runtime

legacy/http: add tests for Content Encoding plugin

---

.changeset/@graphql-mesh_graphql-7411-dependencies.md
packages/legacy/handlers/graphql/package.json
yarn.lock

Includes a fix for sometimes having duplicate type definitions in the generated Mesh artifacts. [See more.](https://github.com/ardatan/graphql-tools/commit/63cab60dca3f36614ff5cb26869e1e7d3e939c50)

fix(legacy/graphql): bump federation tools

---

.changeset/gorgeous-moons-sleep.md
.changeset/twenty-apes-refuse.md
packages/legacy/utils/src/logger.ts

Trimmed messages are annoying and have no real value.
Users should never find themselves in situations where log messages contains mission critical info but are trimmed because DEBUG is not enabled.
Furthermore, no one will know ahead of time that messages are trimmed without DEBUG=1 and until they hit the "Message is too long. Enable DEBUG=1 to see the full message." it might be too late.

fix(utils): DefaultLogger does not trim messages by default and accepts more truthy strings for DEBUG env var

---

.changeset/mighty-flies-wink.md
packages/serve-cli/src/run.ts
packages/serve-runtime/package.json
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/types.ts
packages/serve-runtime/tests/hive.spec.ts
website/src/pages/v1/serve/references/cli.mdx
website/src/pages/v1/serve/references/config.mdx
yarn.lock

If Hive CDN endpoint is provided, the runtime won't introspect the schema from the endpoint, and fetch it from Hive CDN.
By default, Mesh Serve introspects the schema from the endpoint. And it fails, it skips the
validation and schema aware features. But if Hive CDN endpoint and key have been provided in the
configuration, Mesh Serve will fetch the schema from the Hive CDN.
```ts filename="mesh.config.ts"
import { defineConfig } from '@graphql-mesh/serve-cli'
export const serveConfig = defineConfig({
proxy: {
endpoint: 'https://example.com/graphql'
},
hive: {
endpoint: 'https://cdn.graphql-hive.com/artifacts/v1/0123-3434/sdl',
key: 'SOME_HIVE_KEY'
}
})
```

feat(serve-runtime): support Hive CDN as schema source for proxy mode

---

.changeset/shaggy-cycles-eat.md
packages/legacy/cli/src/config.ts

No default importFn for findAndParseConfig, making the processor use utils importFn

---

.changeset/stale-needles-invite.md
examples/openapi-location-weather/tests/__snapshots__/location-weather.test.ts.snap
examples/v1-next/integrations/fastify/tests/fastify.spec.ts
packages/loaders/openapi/tests/example_api.test.ts
packages/loaders/openapi/tests/example_api8.test.ts
packages/transports/common/src/types.ts
packages/transports/rest/src/directives/getTypeResolverForAbstractType.ts
packages/transports/rest/src/directives/httpOperation.ts
packages/transports/rest/src/directives/pubsubOperation.ts
packages/transports/soap/src/executor.ts

Related https://github.com/ardatan/graphql-mesh/issues/7011
Also related https://github.com/ardatan/graphql-tools/pull/6217
Fixes https://github.com/ardatan/graphql-mesh/issues/7035
Introduce a standard Upstream Error Format for HTTP-based sources;
So all sources throw an error will have the extensions in the following format;
```json
{
"extensions": {
"request": { // The details of the request made to the upstream service
"endpoint": "https://api.example.com",
"method": "GET",
},
"response": { // The details of the HTTP response from the upstream service
"status": 401,
"statusText": "Unauthorized",
"headers": {
"content-type": "application/json"
},
"body": { // The raw body returned by the upstream service
"error-message": "Unauthorized access",
}
},
}
}
```

Standard error format in transports (REST, SOAP, GraphQL etc)

---

packages/plugins/response-cache/src/index.ts

* the actual cache entry found for a `responseId` has never been deleted
expected)
- OS:
- NodeJS:
[CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc …

fix: mutation does not delete cache entry

---

.changeset/gentle-pandas-return.md
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/openapi/tests/fixtures/pet.yml

Fixes https://github.com/ardatan/graphql-mesh/issues/7561
Support different ref types in `discriminator.mapping`;
All of the following ref formats are considered as valid;
```yml
discriminator:
mapping:
A: '#/components/schemas/A'
A: 'A'
A: '../components/schemas/A'
```

fix(openapi): support alternative ref types for `discriminator.mapping`

---

.changeset/shiny-dragons-stare.md
packages/fusion/runtime/src/unifiedGraphManager.ts
packages/fusion/runtime/tests/polling.test.ts

If the first poll fails, keep polling but fail on requests
If any poll fails in somewhere, keep polling but keep using the last successful supergraph
So if the CDN is down at some point, the gateway will keep polling the supergraph, but will keep using the last successful supergraph. This is useful for cases where the CDN is down, but the supergraph is still available.

fix(runtime): keep polling even if fetching fails

---

website/src/pages/docs/plugins/plugins-introduction.mdx

I discovered some gaps in the documentation when writing my own custom mesh plugin - now trying to contribute to the docs in hope to help the next person :-) 
This is adding a few points to the plugin introduction docs; points covered are:
- consuming a plugin that is in same codebase and not a individually published package
- linking to envelop plugin lifecycle to show more clearly which other hooks are available
- explain how to update context from within a plugin hook
N/A
N/A
changeset using `yarn changeset` that bumps the version - N/A 
If this is a relatively large or complex change, kick off the discussion by …

docs: extend mesh plugin introductions docs

---

packages/serve-cli/src/cli.ts

Unnecessary log because there's a "starting" log for each of the subcommands. Also, looks hella weird when just printing help.

fix(serve-cli): No "Starting Mesh" log

---

packages/hive-gateway/rollup.binary.config.js
packages/hive-gateway/rollup.config.js
packages/serve-cli/rollup.binary.config.js
packages/serve-cli/rollup.config.js

Much, _much_, shorter stack trace in bundled environments (docker and bin) where imports fail.

Bundle custom import hooks and use path instead of injecting code

---

.github/workflows/release.yml
website/public/install-hive-gateway.sh
website/public/install-mesh-serve.sh

- Add `.gz` extension is missing in the assets of each binary release
- Add `.gz` extension to the installation scripts `install-*.sh`

Fix the asset name of the binary and installation scripts

---

.changeset/chilled-flowers-turn.md
packages/hive-gateway/src/bin.ts
packages/serve-cli/src/bin.ts
packages/serve-cli/src/cli.ts

Suppress Node Warnings, and expose them only if \`DEBUG\` env var is truthy

fix(serve-cli): suppress node warnings by default, and expose them only in debug mode

---

.changeset/light-masks-clean.md
packages/legacy/handlers/mongoose/src/index.ts

When disabling resolvers in the .meshrc configuration files, the Mongoose handler would still try to generate the schema, then fail.
Fixes #6989
expected)
Before the fix, using a configuration similar to this one would cause an error:
```yaml
sources:
- name: [redacted]
handler:
mongoose:
connectionString: '{env.MONGO_DB_CONNECTION_STRING}'
models:
- name: MyModel
path: ./src/models/my-model.ts#MyModel
options:
resolvers:
count: false
```
```
Failed to generate the schema Error: Type MyModel does not have resolver with name 'count'
at ObjectTypeComposer.getResolver (/app/node_modules/graphql-compose/src/ObjectTypeComposer.ts:1306:13)
at /app/node_modules/@graphql-mesh/mongoose/cjs/index.js:80:76
at Array.map (<anonymous>)
at …
```

Fix: filter out disabled operations in Mongoose handler when generating schema (#6989)

---

.changeset/polite-mangos-beg.md
e2e/auto-type-merging/__snapshots__/auto-type-merging.test.ts.snap
e2e/federation-mixed/__snapshots__/federation-mixed.test.ts.snap
e2e/openapi-arg-rename/__snapshots__/openapi-arg-rename.test.ts.snap
e2e/openapi-naming-convention/__snapshots__/openapi-naming-convention.test.ts.snap
e2e/openapi-prune/__snapshots__/openapi-prune.test.ts.snap
e2e/type-merging-batching/__snapshots__/type-merging-batching.test.ts.snap
packages/fusion/composition/src/compose.ts
packages/fusion/composition/src/transforms/hoist-field.ts
packages/fusion/composition/tests/__snapshots__/composition.spec.ts.snap
packages/fusion/runtime/src/federation/subgraph.ts
packages/fusion/runtime/tests/transforms/filter-schema.test.ts
packages/fusion/runtime/tests/transforms/hoist-field.test.ts
packages/fusion/runtime/tests/transforms/naming-convention.test.ts
packages/fusion/runtime/tests/transforms/prefix.test.ts
packages/legacy/transforms/hoist-field/test/transform.spec.ts

If the target hoisted field is a new field name that doesn't exist, create that field and keep the
existing one;
```ts
createHoistFieldTransform({
mapping: [
{
typeName: 'Query',
pathConfig: ['users', 'results'],
newFieldName: 'usersResults',
},
],
})
```
```diff
type Query {
users(limit: Int!, page: Int): UserSearchResult # Keep this
+ usersResults(limit: Int!, page: Int): [User!]! # Add a new one
}
scalar _HoistConfig
type UserSearchResult {
page: Int!
}
type User {
id: ID!
name: String!
}
```

fix(compose/hoist-field): create new field if the target does not exist

---

website/src/pages/_meta.tsx
website/src/pages/v1/getting-started.mdx

This PR adds a `v1` and `v0` links in the header (as in Yoga and Envelop docs)

[docs] Give access to the legacy docs and fix navigation menu

---

.changeset/sharp-dodos-visit.md
packages/fusion/composition/src/transforms/encapsulate.ts
packages/fusion/composition/src/transforms/filter-schema.ts
packages/fusion/runtime/tests/transforms/hoist-field.test.ts

Fixes the error for multiple definitions of `@hidden` directive when encapsulate and filter transforms are used together

fix(composition): do not add multiple `@hidden` directives

---

.changeset/fair-students-tease.md
packages/legacy/utils/src/resolve-additional-resolvers.ts

Allow to provide values instead of only interpolated strings for `additionalArgs`.

[legacy] allow for non string values in additionalArgs

---

.changeset/@graphql-mesh_plugin-hive-7767-dependencies.md
.changeset/@graphql-mesh_serve-runtime-7767-dependencies.md
.changeset/@graphql-mesh_transform-hive-7767-dependencies.md
packages/legacy/transforms/hive/package.json
packages/plugins/hive/package.json
packages/serve-runtime/package.json
yarn.lock

A new version of hive gateway needs to be released as new versions of `@graphql-hive/core` and `@graphql-hive/yoga` were released.

Update Hive libs to latest

---

.changeset/afraid-cycles-reflect.md
e2e/sqlite-chinook/__snapshots__/sqlite-chinook.test.ts.snap
e2e/type-merging-batching/__snapshots__/type-merging-batching.test.ts.snap
packages/fusion/composition/src/compose.ts
packages/fusion/composition/tests/composition.spec.ts
trip.patch

Do not take `barId` matching field and arg as a type merging key
```graphql
type Query {
foo(id: ID!, barId: ID): Foo!
}
type Foo {
id: ID!
barId: ID!
}
```

fix(compose): avoid extra key fields

---

.changeset/big-tigers-sing.md
packages/plugins/opentelemetry/src/plugin.ts
packages/plugins/opentelemetry/tests/useOpenTelemetry.spec.ts
packages/serve-cli/src/commands/proxy.ts
packages/serve-cli/src/commands/subgraph.ts
packages/serve-cli/src/commands/supergraph.ts
packages/serve-cli/src/config.ts

Allow a user to pass `initializeNodeSDK: boolean` option to the `useOpenTelemetry` plugin, in case the userland code already initialized NodeSDK themselves and does not want this plugin to create one. The default behaviour is the same, if you don't pass `initializeNodeSDK` then it will default to true, making this feature backwards compatible.
Fixes #7754
None

`[@graphql-mesh/plugin-opentelemetry]` Make it possible to skip initializing `NodeSDK`

---

.changeset/@graphql-mesh_transport-http-7826-dependencies.md
.changeset/proud-hounds-happen.md
packages/transports/http/package.json
packages/transports/http/src/index.ts
yarn.lock

fix(transport-http): add missing `process` for cross platform support

---

.changeset/@graphql-mesh_transport-ws-7712-dependencies.md
.changeset/breezy-meals-fetch.md
.changeset/fluffy-cycles-jam.md
.changeset/proud-lions-live.md
packages/hive-gateway/rollup.config.js
packages/serve-cli/rollup.config.js
packages/transports/http/src/index.ts
packages/transports/ws/package.json
packages/transports/ws/src/index.ts
packages/transports/ws/tests/ws.spec.ts
yarn.lock

[@graphql-hive/gateway] allow header forwarding for WebSocket transport

---

.changeset/pink-eyes-search.md
e2e/auto-type-merging/__snapshots__/auto-type-merging.test.ts.snap
e2e/federation-mixed/__snapshots__/federation-mixed.test.ts.snap
e2e/hoist-and-prefix-transform/__snapshots__/hoist-and-prefix-transform.test.ts.snap
e2e/manual-transport-def/__snapshots__/manual-transport-def.test.ts.snap
e2e/type-merging-batching/__snapshots__/type-merging-batching.test.ts.snap
packages/compose-cli/src/getComposedSchemaFromConfig.ts
packages/fusion/composition/src/compose.ts
packages/legacy/types/src/config-schema.json
packages/legacy/types/src/config.ts

Do not create extra \`@transport\` annotation if the subgraph is a regular HTTP subgraph

enhance(compose): avoid extra `@transport` annotation if unnecessary

---

.changeset/orange-buttons-end.md
packages/legacy/utils/src/logger.ts

Previously the `isDebug` getter method exclusively checked the env vars; meaning, if LogLevel.debug is supplied without DEBUG=1 in the env, no debug logs will be written. This PR makes sure the `isDebug` method also respects the LogLevel.
Bonus points: simplify stderr usage.

DefaultLogger respects the LogLevel.debug and simplify stderr usage

---

website/src/hotfix.css
website/src/pages/_app.tsx

`--font-sans` isn't resolved, and the entire `font-family` property is skipped because of it.
this fixes the serif font we see in the docs
there's already another fix upstream in Components, but it wasn't merged yet if I remember correctly

hotfix: specify the --font-sans in a .css file

---

.changeset/@graphql-mesh_include-8007-dependencies.md
.changeset/cuddly-spies-argue.md
.changeset/fresh-insects-give.md
.changeset/silver-days-sort.md
.changeset/thick-goats-type.md
packages/fusion/composition/tests/loaders.spec.ts
packages/include/package.json
packages/include/src/index.ts
packages/legacy/cli/src/index.ts
packages/legacy/transforms/hive/src/index.ts
packages/legacy/utils/src/in-context-sdk.ts
packages/loaders/json-schema/src/index.ts
packages/loaders/openapi/src/index.ts
packages/loaders/raml/src/index.ts
yarn.lock

- Do not break the request even if the operation is not able to process
- Do not fail on process termination even if the disposal fails
- Remove the need of mod.default || mod workaround
- Fix import issue of additionalResolvers in mesh dev - Fixes https://github.com/ardatan/graphql-mesh/issues/7963
- Fix passed upstream operation in Hive transform

Fix Hive Transform and additional resolvers import issues

---

.changeset/short-fans-change.md
packages/legacy/transforms/naming-convention/src/bareNamingConvention.ts
packages/legacy/transforms/prefix/src/barePrefix.ts

Hello @ardatan , been a while; so to remind you that you cannot get rid of me, here I am with fresh PR 🙂
This PR fixes the following issues with bare mode transforms.
- The built-in resolver was always applying the prefix to the resolved typeName. Sometimes the typeName might be an extension over a resolver of another field that already went through transformation; hence the prefix might be applied multiple times. This fix ensures the prefix is not applied more than once.
- Bug in the built-in `defaultResolverComposer` causing the return value of an entire original result in place of a single array item
- Added processing of composite fields when enum config is available so that their types get the resolver composer attached
- Prevent mapping of arguments for fields where arguments are …

Fix bare mode resolvers for Prefix and NamingConvention transforms

---

website/tailwind.config.ts

Tailwind wasn't picking up `w-8`. Now it picks it up again.

Add theme.config.tsx to tailwind content

---

.changeset/loud-lemons-press.md
packages/plugins/http-cache/src/index.ts
packages/plugins/http-cache/tests/test-gateway-config.ts

Relax the typings so the plugin can be used as `GatewayPlugin`.
The pointed line was previously failing because `ctx` is `GatewayConfigContext` which has `config` etc as optional,
but the old type of the plugin options was `MeshPluginOptions` which expects `cache`, `pubsub` etc and more things that are not available in `GatewayConfigContext`.
```ts
import { defineConfig, useHttpCache } from '@graphql-hive/gateway';
export const gatewayConfig = defineConfig({
plugins: ctx => [
useHttpCache({
...ctx, // This was failing
})
]
})
```

fix(http-cache): compatibility with `@graphql-hive/gateway`

---

.changeset/wet-timers-decide.md
e2e/type-merging-with-transforms/__snapshots__/type-merging-with-transforms.test.ts.snap
e2e/type-merging-with-transforms/mesh.config.ts
e2e/type-merging-with-transforms/package.json
e2e/type-merging-with-transforms/services/authors.ts
e2e/type-merging-with-transforms/services/books.ts
e2e/type-merging-with-transforms/type-merging-with-transforms.test.ts
packages/legacy/utils/src/in-context-sdk.ts
yarn.lock

The error `context[additionalResolver.sourceName][additionalResolver.sourceTypeName][additionalResolver.sourceFieldName] is not a function` occurs when field names are transformed using transforms. This mismatch prevents proper resolution of the schema field types.
To address this issue, the `applySchemaTransforms` function is now invoked when creating inContextSDK. This ensures that the transformed schema field types are correctly applied, resolving the error and enabling seamless functionality.
Fixes #7742
expected)
Adding links to sandbox …

fix: apply schema transforms from inContextSDK

---

.changeset/odd-pants-sing.md
packages/plugins/jwt-auth/package.json
packages/plugins/jwt-auth/src/index.ts
yarn.lock

fix https://github.com/graphql-hive/gateway/issues/366 rel https://github.com/dotansimha/graphql-yoga/pull/3590
Close: #8190 
- fix: https://github.com/graphql-hive/gateway/issues/366
- related to: https://github.com/dotansimha/graphql-yoga/pull/3590
expected)
reproduce. Please also list any relevant details for your test …

feat: export extractFromConnectionParams from @graphql-yoga/plugin-jwt

---

.changeset/pink-crews-fix.md
packages/legacy/transforms/hive/src/index.ts

In order to prevent Hive Agent to crash, filter non-existing delegated argument while reporting.

fix(transform-hive): filter non-existing delegated argument

---

.changeset/@omnigraph_grpc-8289-dependencies.md
.changeset/large-oranges-draw.md
packages/legacy/handlers/grpc/test/__snapshots__/handler.spec.ts.snap
packages/legacy/handlers/grpc/test/handler.spec.ts
packages/legacy/handlers/grpc/yaml-config.graphql
packages/legacy/handlers/openapi/yaml-config.graphql
packages/legacy/handlers/raml/yaml-config.graphql
packages/legacy/types/src/config-schema.json
packages/legacy/types/src/config.ts
packages/loaders/grpc/package.json
packages/loaders/grpc/src/grpcLoaderHelper.ts
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/openapi/src/types.ts
packages/loaders/raml/src/getJSONSchemaOptionsFromRAMLOptions.ts
packages/loaders/raml/src/types.ts
website/src/generated-markdown/GrpcHandler.generated.md
website/src/pages/v1/source-handlers/grpc.mdx
yarn.lock

Closes https://github.com/ardatan/graphql-mesh/issues/8243
New option `selectQueryOrMutationField` to decide which field belongs to which root type explicitly.
```ts filename="mesh.config.ts"
import loadGrpcSubgraph from '@omnigraph/grpc'
import { defineConfig } from '@graphql-mesh/compose-cli'
export const composeConfig = defineConfig({
subgraphs: [
{
sourceHandler: loadGrpcSubgraph('MyGrpcApi', {
/** .. **/
// Prefix to collect Query method default: list, get
prefixQueryMethod: ['list', 'get'],
// Select certain fields as Query or Mutation
// This overrides `prefixQueryMethod`
selectQueryOrMutationField: [
{
// You can use a pattern matching with *
fieldName: '*RetrieveMovies',
type: 'Query',
},
// Or you can use a specific field name
// This will make the field GetMovie available as a …
```

feat(grpc): `selectQueryOrMutationField`

---

website/src/components/examples-sandbox.tsx

Potential fix for [https://github.com/ardatan/graphql-mesh/security/code-scanning/26](https://github.com/ardatan/graphql-mesh/security/code-scanning/26)
To fix the problem, we need to ensure that the value taken from `e.target.value` is sanitized before it is used to construct the `iframeSrc` URL. This can be done by validating the value against the predefined set of examples (`EXAMPLES`). If the value is not found in the predefined set, we should not use it.
- We will create a function to validate the `exampleDir` value.
- We will use this function to sanitize the value before setting it to the state.
- This ensures that only valid example directories are used in constructing the `iframeSrc` URL.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 26: DOM text reinterpreted as HTML

---

.changeset/tiny-fans-drive.md
packages/string-interpolation/src/interpolator.js

Potential fix for [https://github.com/ardatan/graphql-mesh/security/code-scanning/27](https://github.com/ardatan/graphql-mesh/security/code-scanning/27)
To fix the problem, we should avoid logging sensitive data directly. Instead, we can log a generic error message without including the potentially sensitive `str` variable. This way, we still get notified of errors without risking the exposure of sensitive information.
- Replace the logging statement on line 176 in `packages/string-interpolation/src/interpolator.js` to avoid logging the `str` variable.
- Ensure that the new logging statement provides enough information to debug the issue without exposing sensitive data.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix for code scanning alert no. 27: Clear-text logging of sensitive information

---

.changeset/@graphql-mesh_plugin-response-cache-8334-dependencies.md
.changeset/wicked-schools-wink.md
e2e/cache-control/gateway.config.ts
packages/plugins/response-cache/package.json
packages/plugins/response-cache/src/index.ts
yarn.lock

~~Blocked by https://github.com/n1ru4l/envelop/pull/2392~~
Fixes https://github.com/graphql-hive/gateway/issues/542
When a subgraph returns cache control headers with a certain TTL, respect that during the calculation of overall TTL in the response cache plugin.
So this removes the extra configuration in the test, TTL is inherited from the subgraph response automatically.
For example, if there is a subgraph using Apollo Server that defines the default TTL without any `@cacheControl` directives. It prevents the response cache plugin to set the TTL infinite(which is the default of the response-cache plugin)

fix(response-cache): respect subgraph cache control TTL value

---

.changeset/sad-queens-own.md
e2e/openapi-javascript-wiki/__snapshots__/openapi-javascript-wiki.test.ts.snap
e2e/openapi-javascript-wiki/mesh.config.ts
packages/compose-cli/src/getComposedSchemaFromConfig.ts

When there is a field in the subgraph that is extended in additionalTypeDefs, do not add `@additionalField`
Ref GW-196

fix(compose): do not add `@additionalField` if the field already exists from a subgraph

---

packages/loaders/openapi/tests/repros.test.ts

Reproduction MESH-233 - Null URL fields should return null not Invalid URL

---

e2e/petstore-subgraph/__snapshots__/petstore-subgraph.test.ts.snap
e2e/petstore-subgraph/mesh.config.ts
e2e/petstore-subgraph/petstore-subgraph.test.ts

- Generate a subgraph SDL with `mesh-compose -o subgraph.sdl --subgraph=petstore` then compose it with Hive
Ref GW-226

Test if the generated subgraph is compatible with Hive Console composition

---

.changeset/clear-dryers-nail.md
packages/plugins/response-cache/src/index.ts

Related to GW-295
When used with `createGatewayRuntime`, there is no default `cache` instance created, which leads to a unwelcoming `cannot read 'get' of undefined` at query time.
This PR introduces an error at gateway initialization time, so that the gateway doesn't start if a `cache` instance is not configured.

fix(response-cache): Check for the presence of a cache instance

---

.changeset/social-pots-obey.md
e2e/openapi-hateoas/__snapshots__/openapi-hateoas.test.ts.snap
e2e/openapi-hateoas/products.json
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts

Fix the HATEOAS link reference anonymization process.
Let's say we have these operations:
- Operation A: `/users/{userId}`
- Operation B: `/users/{id}/contracts/{contractId}`
With A (user) linking through HATEOAS to multiple B (contracts).
There is a double need:
1. To anonymize the argument names (this part was already implemented)
2. Ensure the anonymization process keeps the operationId identifiable (this is the buggy part)
The current HATEOAS href anonymization **removes** arguments, whereas we need to keep track of their presence in order not to target the wrong operations at runtime.
Fixes #8636
**In the first commit, it shows how the issue is reproduces, and the other one fixes it.**
Against a cohesive bundle of 800+ local swaggers. …

fix(openapi): HATEOAS href anonymization

---

.changeset/strong-melons-like.md
.gitignore
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/openapi/tests/hateoas-ordering.test.ts

The fix ensures that **there is no correct or incorrect order of swaggers** - whatever their order, schema loading and HATEOAS cross-referencing works reliably through coordinated batch processing with proper dependency resolution.
**Core Issue**: HATEOAS support was unreliable due to order dependency - when Schema A referenced operations from Schema B, it would fail if Schema A was loaded before Schema B.
**Solution**: Implemented context-aware batch loading that resolves cross-schema dependencies regardless of loading order.
Fixes #8654
- OS:
- NodeJS:
- Added …

fix(openapi): HATEOAS: resolve cross-schema dependencies regardless of loading order

---

.changeset/some-spoons-lead.md
packages/legacy/handlers/mysql/src/index.ts
packages/legacy/handlers/mysql/test/handler.spec.ts
packages/loaders/mysql/src/schema.ts
packages/loaders/mysql/tests/__snapshots__/schema.test.ts.snap
packages/loaders/mysql/tests/schema.test.ts

- The change is too small for a separate issue. If I missed something and discussion is worth it I can still create an issue, though
The `tables` and `tableFields` config options are defined in the MySQLHandler types and partially used inside `loadGraphQLSchemaFromMySQL` from `@omnigraph/mysql`. However,  they were not properly being passed down to the `handleTableName` function in the omnigraph schema. 
Moreover, I also fixed the legacy mysql handler to pass down both `tables` and `tableFieldsConfig`.
- no official issue reported.
- implicitly fixing/making `tables` and …

fix(mysql): Propagate tables and tableNames options to loader
