examples/postgres-geodb/.meshrc.yaml
examples/postgres-geodb/README.md
packages/runtime/src/parse-config.ts

Related: https://github.com/Urigo/graphql-mesh/issues/67

Added support for env vars in config file

---

.vscode/settings.json
examples/country-info/.meshrc.yml
examples/javascript-wiki/.meshrc.yaml
examples/location-weather/.meshrc.yaml
examples/postgres-geodb/.meshrc.yaml
packages/handlers/graphql/src/index.ts
packages/handlers/graphql/yaml-config.graphql
packages/handlers/grpc/src/index.ts
packages/handlers/grpc/yaml-config.graphql
packages/handlers/json-schema/src/index.ts
packages/handlers/json-schema/yaml-config.graphql
packages/handlers/openapi/src/index.ts
packages/handlers/openapi/test/handler.spec.ts
packages/handlers/openapi/yaml-config.graphql
packages/handlers/postgraphile/src/index.ts
packages/handlers/postgraphile/yaml-config.graphql
packages/handlers/soap/src/index.ts
packages/handlers/soap/yaml-config.graphql
packages/runtime/src/get-mesh.ts
packages/runtime/src/parse-config.ts
packages/runtime/src/types.ts
packages/runtime/yaml-config.graphql
packages/types/package.json
packages/types/src/config-schema.json
packages/types/src/index.ts
yarn.lock

Move `source` to the right place, fixes validations 
Still need to fix more stuff with JSON schema validations, will fix it later.

Align all configuration issues

---

README.md

Added missing package to go through README tutorial

Update Installation section in README

---

packages/handlers/openapi/src/index.ts
packages/handlers/openapi/yaml-config.graphql

related https://github.com/Urigo/graphql-mesh/issues/187

Added `schemaHeaders` to openapi config

---

.vscode/settings.json
packages/handlers/json-schema/src/json-schema-types.ts
packages/handlers/json-schema/src/json-schema-visitor.ts

Fix array items in JSON Schema Handler

---

package.json
patches/@docusaurus+plugin-sitemap+2.0.0-alpha.50.patch
yarn.lock

This patch can be removed in next alpha version of docusaurus

Fix sitemap

---

packages/handlers/openapi/src/index.ts
packages/handlers/openapi/src/openapi-to-graphql/index.ts
packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts
packages/handlers/openapi/test/example_api2_server.ts
packages/handlers/openapi/test/example_api3_server.ts
packages/handlers/openapi/test/example_api5_server.ts
packages/handlers/openapi/test/example_api6_server.ts
packages/handlers/openapi/test/example_api_server.ts

Do not modify headers globally in OpenAPI handler

---

examples/json-schema-example/example-query.graphql
examples/json-schema-example/json-schemas/company.json
examples/postgres-geodb/src/test-sdk.ts
packages/handlers/json-schema/src/json-schema-types.ts
packages/handlers/json-schema/src/json-schema-visitor.ts
packages/handlers/odata/src/index.ts
packages/handlers/postgraphile/package.json
packages/runtime/src/get-mesh.ts
packages/runtime/src/utils.ts

- Support non compliant enum values #425
- Support named enum definitions #424

Fix Enum Support on JSON Schema Handler

---

README.md

Corrects 2 typos in Readme.md

---

website/docs/transforms/filter-schema.md

Corrects type in filter-schema.md

---

packages/mergers/federation/src/index.ts
packages/mergers/stitching/package.json
packages/mergers/stitching/src/index.ts

Fix root level transforms

---

packages/cli/src/commands/typescript.ts
packages/mergers/federation/src/index.ts
packages/mergers/stitching/package.json
packages/mergers/stitching/src/index.ts
packages/runtime/src/resolvers-hooks.ts

Use correct subschema for in-context SDK

---

packages/cli/src/commands/typescript.ts
packages/mergers/federation/src/index.ts
packages/mergers/stitching/package.json
packages/mergers/stitching/src/index.ts
packages/runtime/src/resolvers-hooks.ts
packages/transforms/cache/package.json
packages/transforms/cache/src/compute-cache-key.ts
packages/transforms/cache/yaml-config.graphql
schema.graphql

Respect selected fields on caching transform

---

packages/transforms/cache/test/cache.spec.ts
packages/transforms/naming-convention/test/naming-convention.spec.ts

Improve the tests of naming convention transform for input types

---

packages/cli/src/commands/typescript.ts
packages/runtime/src/get-mesh.ts
packages/runtime/src/resolvers-hooks.ts
packages/runtime/src/types.ts

Add original context object as target in proxyContext

---

packages/handlers/postgraphile/src/index.ts

Related https://github.com/Urigo/graphql-mesh/issues/583#issuecomment-654464874

Fix Postgraphile Plugins support

---

packages/handlers/graphql/src/index.ts
packages/handlers/openapi/src/index.ts
packages/handlers/openapi/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
schema.graphql

feat(openapi): support query string interpolation

---

packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts

See https://github.com/IBM/openapi-to-graphql/pull/325/files

fix(openapi): don't set request content type if body is empty

---

examples/odata-microsoft/.meshrc.yml
examples/odata-microsoft/package.json
examples/openapi-javascript-wiki/src/mesh/sdk.ts
packages/handlers/odata/src/index.ts
packages/handlers/odata/test/__snapshots__/handler.spec.ts.snap
packages/handlers/odata/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
packages/utils/src/read-file-or-url.ts
schema.graphql
yarn.lock

- Support custom metadata file from FileSystem
- Fix DateTimeOffset scalar
- Fix handling multiple schema namespaces
- Add `beta` endpoint to `odata-microsoft` example

OData Improvements

---

.changeset/quiet-ladybugs-count.md
packages/transforms/filter-schema/src/index.ts
packages/transforms/rename/src/index.ts

fix(transforms): apply transforms for input object type fields

---

.changeset/slow-pumas-smile.md
packages/runtime/src/resolvers-hooks.ts

fix(runtime): handle non query operations in proxy sdk

---

.changeset/clean-radios-roll.md
packages/handlers/openapi/src/index.ts

fix(openapi): handle missing baseUrl properly

---

website/docs/transforms/cache.md

let me know if I need to do anything more :)

Update cache.md docs

---

.changeset/silent-ears-compare.md
packages/handlers/odata/src/index.ts
packages/handlers/odata/test/__snapshots__/handler.spec.ts.snap

fix(odata): add $count to odata query options

---

.changeset/swift-zoos-wait.md
packages/mergers/stitching/src/mergeSingleSchema.ts

fix(merging): apply additionalTypeDefs after wrapping the schema

---

.changeset/bright-mice-joke.md
packages/runtime/src/get-mesh.ts

fix(runtime): apply noWrap transforms as wrap transforms if schema is wrapped already

---

README.md

A lot of people are using Mesh in production.
Also as a gateway.

Remove old comments

---

website/docs/getting-started/basic-example.md

Fix wiki example link

---

.changeset/purple-socks-wink.md
packages/runtime/src/resolvers-hooks.ts

fix(runtime): map schemas to rawSources correctly

---

packages/handlers/json-schema/src/index.ts
packages/handlers/json-schema/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
packages/utils/src/resolver-data-factory.ts

feat(json-schema): add argTypeMap to operation config to provide custom types for args

---

.changeset/unlucky-boxes-repeat.md
packages/cli/src/commands/typescript.ts
yarn.lock

fix(cli): generate typescript definitions properly

---

.changeset/eight-hounds-jump.md
packages/cli/package.json

fix: generated typescript IsTypeOfResolverFn type arguments

---

.changeset/strong-ladybugs-shop.md
packages/config/src/index.ts

The PR fixes my issue #1289
Is there something else changes I should do to get it released?

config: specified return type for processConfig to fix generated .d.ts

---

.changeset/ten-terms-deliver.md
packages/transforms/rename/src/index.ts
packages/transforms/rename/test/__snapshots__/rename.spec.ts.snap
packages/transforms/rename/test/rename.spec.ts
packages/transforms/rename/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/docs/transforms/rename.md

feat(rename): support rename transform

---

.changeset/odd-islands-judge.md
packages/cli/src/index.ts
website/docs/getting-started/basic-example.md

For dumping the Mesh schema to a static file (for better integration with other tools and IDEs)

Added `schema` command to cli

---

website/docs/getting-started/multiple-apis.md

Now refers to the past tense of to have

Small tense improvement

---

website/docs/transforms/encapsulate.md

I ran into some problems using this transformer - I got a 500 error in graphiql, though the server seemed to compile okay. It turned out it was due to mutation and subscription defaulting to true, so for the example I added those options set to false. Also did some grammar fixes.

Update encapsulate.md docs

---

.changeset/red-wombats-promise.md
examples/mysql-employees/README.md
packages/handlers/mysql/src/index.ts

fix(mysql): fix foreign table references

---

.changeset/thick-mangos-lie.md
packages/cli/src/commands/serve/serve.ts

Related https://github.com/Urigo/graphql-mesh/discussions/1664

enhance(serve): run custom handlers before anything else

---

.changeset/loud-walls-work.md
.changeset/serious-bees-sniff.md
examples/openapi-location-weather/tests/__snapshots__/location-weather.test.js.snap
packages/handlers/grpc/src/utils.ts
packages/handlers/grpc/test/__snapshots__/handler.spec.ts.snap
packages/handlers/grpc/test/fixtures/proto-tests/custom-message.proto
packages/handlers/grpc/test/handler.spec.ts

gRPC Fixes

---

.changeset/curvy-lizards-dance.md
packages/handlers/openapi/src/index.ts

https://github.com/Urigo/graphql-mesh/issues/1775

openapi use qs

---

.changeset/spicy-ants-judge.md
declarations.d.ts
packages/config/src/index.ts
packages/handlers/json-schema/src/declarations.d.ts
tsconfig.json

Related https://github.com/Urigo/graphql-mesh/issues/1791

fix(config): move Object.keys fix outside of source code

---

.changeset/sixty-pumas-drum.md
packages/utils/src/read-file-or-url.ts

https://github.com/Urigo/graphql-mesh/issues/1742

use fallbackFormat in readUrlWithCache

---

.changeset/yellow-frogs-collect.md
packages/cli/src/index.ts
packages/transforms/snapshot/src/index.ts
packages/utils/src/fs-operations.ts

chore: mkdir before emit output

---

.changeset/yellow-paws-mate.md
packages/handlers/grpc/src/index.ts

feat(grpc): ignore packages starts with `grpc.*`

---

website/docusaurus.config.js
website/package.json

Algolia Search configuration removal. Component moved to TGC.
https://github.com/the-guild-org/the-guild-components

Algolia Config Removal

---

website/docs/handlers/available-handlers.md

Mysql deep link leads to SQLite

---

.changeset/fair-dancers-fail.md
packages/config/src/index.ts
packages/config/yaml-config.graphql
packages/runtime/src/types.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
packages/types/src/index.ts

https://github.com/Urigo/graphql-mesh/discussions/1833

WIP: Type merging

---

website/docs/getting-started/basic-example.md

clarifying format switch for exports.
https://github.com/Urigo/graphql-mesh/discussions/2089#discussioncomment-730172
Update to docs
Documentation update for clarification
Documentation update for clarification
n/a

clarifying the dump-schema command

---

.changeset/tiny-gifts-change.md
packages/cli/src/commands/typescript.ts

fix(cli): fix duplicate methods in incontext sdk typings

---

website/docs/recipes/as-gateway.md

Fixes # https://github.com/Urigo/graphql-mesh/issues/2168
- [] I have performed a self-review of my own code

Extend the documentation with the --dir option

---

.changeset/late-dodos-return.md
packages/handlers/grpc/src/index.ts
packages/handlers/grpc/test/__snapshots__/handler.spec.ts.snap
packages/handlers/grpc/test/handler.spec.ts

fixed trivial warns I found while editing something other here :P

chore: trivial changes for grpc handler

---

website/docs/cache/inmemory-lru.md

incorrect casing leads to failure with unclear error

---

.changeset/early-bears-tap.md
packages/transforms/cache/package.json
packages/transforms/cache/src/compute-cache-key.ts
yarn.lock

fix(transform-cache): handle aliases correctly

---

.changeset/dull-papayas-decide.md
packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts
packages/handlers/openapi/test/fixtures/example_oas.json

fix(openapi): respect nullable property

---

.changeset/nervous-emus-protect.md
packages/transforms/mock/package.json
packages/transforms/mock/src/index.ts

Apply mocks for GraphQL Scalars

---

.changeset/silver-drinks-repair.md
packages/cache/redis/src/index.ts
packages/cache/redis/test/cache.spec.ts
packages/cache/redis/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts

Fixes #2541
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …

feat(redis): add support for url

---

packages/handlers/odata/src/index.ts
packages/handlers/odata/test/__snapshots__/handler.spec.ts.snap
packages/handlers/odata/test/fixtures/simple-metadata.xml
packages/handlers/odata/test/handler.spec.ts

Fixes #2557 
I've added a new test case to demonstrate the bug:
After applying the fix:
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

Fix OData handler support for bound functions with entity set paths

---

.changeset/small-ants-breathe.md
packages/handlers/mysql/src/index.ts
packages/handlers/mysql/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts

```yml
tables: 
- employees
- jobs
- others
tableFields:
- table: employees
fields: 
- id
```

feat(mysql): ability to select some specific tables

---

.changeset/slimy-mangos-grab.md
packages/cli/src/commands/generate-operations.ts
packages/cli/src/commands/serve/yaml-config.graphql
packages/cli/src/commands/ts-artifacts.ts
packages/cli/src/index.ts
packages/types/src/config-schema.json
packages/types/src/config.ts

```yaml
sdk:
generateOperations:
selectionSetDepth: 2
```

feat(cli): generate operations for sdk

---

.changeset/odd-cycles-dream.md
packages/handlers/openapi/src/index.ts

fix(openapi): interpolate baseUrl string

---

README.md

Fix broken link in README.md for Supported APIs

---

website/docs/transforms/encapsulate.md

missing colon after `encapsulate`

---

packages/transforms/prefix/src/barePrefix.ts

Fix typo.
Does not affect functionality at all.

Fix prefix typo

---

.changeset/stale-bugs-cheat.md
website/docs/transforms/replace-field.md
website/sidebars.js

Quick PR mostly to add replace-field transform to sidebar.
Apologies this was forgotten in previous PR.

More references for replace-field transform

---

website/docs/recipes/as-gateway.md

Improve explanation about the `serve` config of `.meshrc.yaml` in file `website/docs/recipes/as-gateway.md`.
- Documentation update

Improve explanation about the `serve` config

---

.changeset/kind-spoons-wonder.md
examples/odata-msgraph-programmatic/index.js
examples/odata-msgraph-programmatic/package.json
packages/store/src/index.ts

enhance(store): use cjs extension for artifacts to support Node ESM

---

packages/cache/inmemory-lru/src/index.ts
packages/transforms/cache/src/compute-cache-key.ts
packages/transforms/cache/src/index.ts
packages/transforms/cache/test/cache.spec.ts

I have added a lot of comments especially in the setShouldWait method as it might seem like certain code is duplicated for no reason.

Prevent race condition + Eliminate local race condition

---

website/docs/recipes/as-gateway.md
website/docs/recipes/as-sdk.md

* Add video embed for "Mesh as Gateway" 📺 
* Add video embed for "Mesh as SDK" 📺

docs(recipes): add wtf videos

---

.changeset/flat-colts-cheat.md
.changeset/strong-ways-rest.md
examples/json-schema-example/tsconfig.json
packages/cli/src/commands/ts-artifacts.ts
packages/cli/src/index.ts
packages/cli/src/utils.ts
packages/mergers/stitching/package.json

Related #3694
> I added another fix to this PR which is not directly related but probably missed while fixing implicit dependencies

Support comments in TSConfig file

---

website/docs/handlers/json-schema.mdx

Closes #3698 
Things to improve:

Add Mesh Sample section 

---

.changeset/quick-dolphins-perform.md
packages/transforms/rename/src/wrapRename.ts
packages/transforms/rename/test/__snapshots__/wrapRename.spec.ts.snap
packages/transforms/rename/test/wrapRename.spec.ts

Closes https://github.com/Urigo/graphql-mesh/issues/3778#issuecomment-1084260358
Related to https://github.com/Urigo/graphql-mesh/pull/3780
cc @santino

fix(transform/rename): argument wrap mode rename

---

.changeset/lazy-cooks-tell.md
packages/handlers/grpc/src/index.ts

Fixes #3798 (issue)
[codesandbox](https://codesandbox.io/s/patient-shape-wi8zci?file=/package.json:136-139)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …

if the endpoint includes the environment, we have to interpolate

---

website/package.json
yarn.lock

cf https://github.com/the-guild-org/the-guild-docs/pull/551

fix(esm): `the-guild-docs` mermaid version pinned

---

website/next.config.mjs
website/package.json
website/src/components/live-demo/index.tsx
website/src/pages/_document.tsx
yarn.lock

The `load` event is now called at 700ms (vs 2s before)

Lazy-load codesandbox

---

.changeset/sharp-flies-dance.md
.changeset/short-cougars-develop.md
.changeset/tidy-horses-move.md
.github/workflows/canary.yml
.github/workflows/release.yml
.github/workflows/tests.yml
examples/json-schema-subscriptions/package.json
examples/openapi-subscriptions/package.json
package.json
packages/handlers/graphql/package.json
packages/handlers/odata/package.json
packages/handlers/openapi/package.json
packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
packages/json-machete/package.json
packages/json-machete/src/compareJSONSchemas.ts
packages/json-machete/src/dereferenceObject.ts
packages/json-machete/tests/compareJSONSchemas.test.ts
packages/loaders/json-schema/package.json
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/raml/package.json
packages/string-interpolation/package.json
packages/string-interpolation/src/interpolator.js
packages/utils/package.json
yarn.lock

Related https://github.com/Urigo/graphql-mesh/issues/3830

Use platform agnostic json-pointer instead of json-ptr

---

packages/types/src/config-schema.json
packages/types/src/config.ts
website/docs/transforms/prune.mdx
website/package.json
website/routes.ts
website/src/pages/docs/[[...slug]].tsx
yarn.lock

Related to https://github.com/Urigo/graphql-mesh/issues/3926

doc: Prune tranform

---

.changeset/popular-ties-matter.md
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/json-schema/test/execution.test.ts

Do not send header if the value is empty

---

.changeset/bright-readers-hope.md
examples/openapi-jira/tests/__snapshots__/jira.test.js.snap
examples/openapi-jira/tests/jira.test.js
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
website/docs/generated-markdown/ServeConfig.generated.md

Do not visit union elements if links or exposeResponseMetadata is not used during schema generation

---

.changeset/wild-countries-travel.md
packages/handlers/json-schema/src/index.ts
packages/handlers/json-schema/yaml-config.graphql
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/json-schema/src/bundle.ts
packages/loaders/json-schema/src/getGraphQLSchemaFromDereferencedJSONSchema.ts
packages/loaders/json-schema/src/loadGraphQLSchemaFromJSONSchemas.ts
packages/loaders/json-schema/src/types.ts
packages/loaders/json-schema/test/execution.test.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
website/docs/generated-markdown/JsonSchemaHandler.generated.md
website/docs/generated-markdown/JsonSchemaHandlerBundle.generated.md
website/docs/generated-markdown/QueryStringOptions.generated.md

Added configurable query string "indices" option for json-schema

feat(json-schema): configuration for query stringify

---

.github/workflows/dependencies-changesets.yml

added deps/changesets workflow

---

website/src/pages/docs/guides/extending-unified-schema.mdx

Fixe a broken links in extending-unified-schema page …

fix broken combine-multiple-sources link in docs

---

packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/openapi/tests/example_api.test.ts

Add tests and fixes for handling multiple sources for openAPI arguments (both query and header arguments)

Openapi multiple argument sources fix

---

website/src/pages/docs/getting-started/overview.mdx

Fixes #4332
Not tested. Just changed the link to the correct one.
N/A

fix broken "your first mesh gateway" link

---

.changeset/afraid-feet-develop.md
packages/runtime/package.json
packages/runtime/src/useSubschema.ts
packages/runtime/test/runtime.spec.ts
packages/runtime/test/useSubschema.test.ts

fix(runtime): if there is only one source, respect introspection query even if there is no operationName

---

.changeset/chilly-ducks-bake.md
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/json-schema/src/types.ts
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/openapi/tests/explode.test.ts
packages/loaders/openapi/tests/fixtures/explode.yml

Fixes https://github.com/Urigo/graphql-mesh/issues/1255
Closes https://github.com/Urigo/graphql-mesh/issues/4240

Respect OpenAPI 'explode' parameter

---

.changeset/nine-buckets-provide.md
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/openapi/tests/__snapshots__/basket.test.ts.snap
packages/loaders/openapi/tests/basket.test.ts
packages/loaders/openapi/tests/fixtures/basket.json

fix(openapi): allow user to override accept from the schema

---

.changeset/mean-worms-approve.md
packages/handlers/grpc/src/index.ts
packages/handlers/grpc/test/__snapshots__/handler.spec.ts.snap
packages/handlers/grpc/test/fixtures/proto-tests/map.proto
packages/handlers/grpc/test/handler.spec.ts

Fixes https://github.com/Urigo/graphql-mesh/issues/4351

fix(grpc): handle maps as JSON scalar

---

.changeset/sour-birds-study.md
.changeset/strange-boxes-greet.md
examples/json-schema-fhir/tests/__snapshots__/fhir.test.js.snap
examples/openapi-javascript-wiki/tests/__snapshots__/javascript-wiki.test.js.snap
packages/json-machete/src/healJSONSchema.ts
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/src/getValidTypeName.ts
packages/loaders/json-schema/test/getComposerFromSchema.test.ts
packages/loaders/openapi/tests/__snapshots__/ibm_language_translator.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/jira.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/stripe.test.ts.snap

Closes https://github.com/Urigo/graphql-mesh/issues/4425#issuecomment-1235478103

fix(json-schema): improvements on handling different formats

---

website/src/pages/docs/getting-started/your-first-mesh-gateway.mdx

**I Assume the above doesn't really apply for a minor documentation update**

Fix broken link to old how-to url

---

website/src/pages/docs/guides/error-masking.mdx
website/src/pages/docs/guides/meta.json

Rename Error Handling to Error Masking

---

website/src/pages/docs/plugins/operation-field-permissions.mdx

chore(docs): fix operation-field-permissions docs

---

.changeset/lucky-jokes-occur.md
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/json-schema/src/getTypeResolverFromOutputTCs.ts
packages/loaders/openapi/tests/__snapshots__/example_api8.test.ts.snap
packages/loaders/openapi/tests/example_api8.test.ts
packages/loaders/openapi/tests/example_api8_server.ts
packages/loaders/openapi/tests/fixtures/example_oas8.json

fix(json-schema): handle untyped http status codes correctly

---

.changeset/itchy-ties-double.md
packages/handlers/openapi/yaml-config.graphql
packages/handlers/raml/yaml-config.graphql
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/openapi/src/types.ts
packages/loaders/raml/src/getJSONSchemaOptionsFromRAMLOptions.ts
packages/loaders/raml/src/types.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
website/src/generated-markdown/OpenapiHandler.generated.md
website/src/pages/docs/migration/openapi-0.31-0.32.mdx

Allow pascal `selectQueryOrMutationField` values
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did …

Allow pascal `selectQueryOrMutationField` values

---

.changeset/late-jeans-begin.md
packages/json-machete/src/healUntitledDefinitions.ts
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/openapi/tests/fixtures/subscriptionType.yml
packages/loaders/openapi/tests/schemas.test.ts

fix(openapi): avoid conflicts with the predefined `Subscription` type definitions

---

website/src/pages/docs/guides/headers.mdx
website/src/pages/docs/handlers/graphql.mdx
website/src/pages/docs/handlers/json-schema.mdx
website/src/pages/docs/handlers/odata.mdx
website/src/pages/docs/handlers/openapi.mdx
website/src/pages/docs/handlers/thrift.mdx

Headers designated doc

---

packages/config/src/process.ts

This fixes a unused import when there are no documents defined. Otherwise it conflicts with eslint.
Fixes #4882
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Fix unused import printWithCache running eslint

---

packages/handlers/graphql/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/src/pages/docs/getting-started/customize-mesh-server.mdx
website/src/pages/docs/getting-started/deploy-mesh-gateway.mdx

Add subscriptionsEndpoint property to config so it does not throw error.
Also, this PR contains minor docs additions
Fixes #4994
No tests defined
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Improve docs, add subscriptionsEndpoint to config

---

.changeset/long-phones-kiss.md
.changeset/orange-rice-approve.md
packages/cache/redis/src/index.ts
packages/cli/src/config.ts

Closes https://github.com/Urigo/graphql-mesh/issues/5059

Stabilize redis configuration handling and improve config validation messages

---

website/src/pages/docs/cli-commands.mdx

Replace broken links

---

website/src/components/index-page.tsx

Very minor homepage UI fix

---

.changeset/@graphql-mesh_grpc-5215-dependencies.md
.changeset/@graphql-mesh_mysql-5215-dependencies.md
.changeset/@graphql-mesh_neo4j-5215-dependencies.md
.changeset/@graphql-mesh_odata-5215-dependencies.md
.changeset/@graphql-mesh_plugin-mock-5215-dependencies.md
.changeset/@graphql-mesh_thrift-5215-dependencies.md
.changeset/@graphql-mesh_transform-naming-convention-5215-dependencies.md
.changeset/@graphql-mesh_transform-prefix-5215-dependencies.md
.changeset/@graphql-mesh_transform-rename-5215-dependencies.md
.changeset/@omnigraph_json-schema-5215-dependencies.md
.changeset/@omnigraph_soap-5215-dependencies.md
packages/handlers/grpc/package.json
packages/handlers/mysql/package.json
packages/handlers/neo4j/package.json
packages/handlers/odata/package.json
packages/handlers/thrift/package.json
packages/loaders/json-schema/package.json
packages/loaders/openapi/tests/example_api.test.ts
packages/loaders/openapi/tests/fixtures/int64-with-defaults.yml
packages/loaders/openapi/tests/schemas.test.ts
packages/loaders/soap/package.json
packages/plugins/mock/package.json
packages/transforms/naming-convention/package.json
packages/transforms/prefix/package.json
packages/transforms/rename/package.json
yarn.lock

Fixes https://github.com/Urigo/graphql-mesh/issues/5214

Bump GraphQL Scalars to support default argument values for BigInt

---

.changeset/kind-dragons-check.md
packages/handlers/thrift/src/index.ts
packages/handlers/thrift/test/__snapshots__/handler.spec.ts.snap
packages/handlers/thrift/test/fixtures/calc.thrift
packages/handlers/thrift/test/fixtures/calc_types.thrift
packages/handlers/thrift/test/handler.spec.ts

Fixes https://github.com/Urigo/graphql-mesh/issues/5212

fix(thrift): support imports

---

.changeset/good-eagles-cover.md
packages/cli/src/commands/ts-artifacts.ts
packages/cli/src/index.ts
packages/config/src/utils.ts
packages/handlers/json-schema/src/index.ts
packages/handlers/neo4j/src/index.ts
packages/handlers/openapi/src/index.ts
packages/handlers/raml/src/index.ts
packages/handlers/soap/src/index.ts

Closes https://github.com/Urigo/graphql-mesh/issues/5202

Fix import issues

---

.changeset/silly-meals-learn.md
packages/plugins/http2/src/index.ts
packages/plugins/mock/src/index.ts
packages/transforms/naming-convention/src/bareNamingConvention.ts
packages/transforms/naming-convention/test/bareNamingConvention.spec.ts
packages/types/src/config-schema.json
packages/types/src/config.ts
website/src/generated-markdown/MockingConfig.generated.md
yarn.lock

Fixes https://github.com/Urigo/graphql-mesh/issues/4895
Closes https://github.com/Urigo/graphql-mesh/pull/5280

Fix naming nested inputs

---

.github/workflows/release.yml

@Urigo please make sure to remove all ALGOLIA-related secrets, except `ALGOLIA_ADMIN_API_KEY`

Algolia cleanup

---

examples/fastify/.meshrc.yml
examples/fastify/src/upstream.ts
examples/fastify/swagger/pets.json
examples/fastify/tests/fastify.spec.ts

PR to test a fastify bug with mesh
expected)
- OS:
- NodeJS: …

Fastify Integration Tests: Unexpected response error

---

.changeset/plenty-turkeys-marry.md
packages/transforms/filter-schema/src/bareFilter.ts
packages/transforms/filter-schema/src/wrapFilter.ts
packages/transforms/filter-schema/test/transform.spec.ts

fix(filter-schema): remove root types with no field left

---

website/src/pages/docs/handlers/openapi.mdx

Website/docs: Fix 404 pages

---

.changeset/twelve-pens-float.md
packages/json-machete/src/visitJSONSchema.ts
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/src/getReferencedJSONSchemaFromOperations.ts
packages/loaders/openapi/package.json
packages/loaders/openapi/src/getJSONSchemaOptionsFromOpenAPIOptions.ts
packages/loaders/openapi/tests/__snapshots__/spotify.test.ts.snap
packages/loaders/openapi/tests/fixtures/pet.yml
packages/loaders/openapi/tests/pet.test.ts
packages/loaders/openapi/tests/schemas.test.ts
yarn.lock

fix(openapi): handle inheritance correctly

---

website/src/pages/docs/getting-started/overview.mdx
website/src/pages/docs/guides/monitoring-and-tracing.mdx
website/src/pages/docs/plugins/response-caching.mdx

Special thanks for this awesome project. 😉 
This PR contains just some minor fixes on the website docs that I realized when I was using the project.

Docs: small fixes on the docs website

---

.changeset/silly-maps-tickle.md
packages/loaders/json-schema/src/directives.ts
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/src/getUnionTypeComposers.ts
packages/loaders/json-schema/test/getComposerFromSchema.test.ts
packages/loaders/openapi/tests/__snapshots__/cloudflare.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/looker.test.ts.snap
packages/loaders/openapi/tests/__snapshots__/nested-one-of.test.ts.snap
packages/loaders/openapi/tests/fixtures/algolia-subset-nested-one-of.yml
packages/loaders/openapi/tests/nested-one-of.test.ts

fix(json-schema): unions with nested arrays

---

.changeset/five-rabbits-grin.md
packages/handlers/mysql/src/index.ts
packages/handlers/mysql/yaml-config.graphql
packages/types/src/config-schema.json
packages/types/src/config.ts
website/src/generated-markdown/MySQLHandler.generated.md

Fixes https://github.com/Urigo/graphql-mesh/issues/5653
New configuration options for SSL;
```
ssl:
ca: PATH_TO_YOUR_CA
```

feat(mysql): SSL Configuration

---

.changeset/perfect-readers-judge.md
packages/handlers/thrift/src/index.ts
packages/handlers/thrift/test/__snapshots__/handler.spec.ts.snap
packages/handlers/thrift/test/fixtures/recursive_types.thrift
packages/handlers/thrift/test/handler.spec.ts

Fix thrift handler causing a crash at startup on recursive structs.
Fixes #5702 

fix thrift recursive structs

---

package.json

Added package manager with Yarn 1 to package.json, this makes sure yarn 1 is used when yarn 2 or 3 is installed using corepack.
Fixes #
expected)
- OS:
- NodeJS: …

chore: add package manager field

---

.changeset/@graphql-mesh_runtime-6070-dependencies.md
packages/handlers/grpc/test/__snapshots__/handler.spec.ts.snap
packages/runtime/package.json

Bump GraphQL JIT plugin to pin the working version

---

.changeset/gold-cheetahs-retire.md
packages/loaders/json-schema/src/getTypeResolverFromOutputTCs.ts
packages/loaders/openapi/tests/__snapshots__/oneof-without-descriminator.test.ts.snap
packages/loaders/openapi/tests/fixtures/one-of-no-discriminator.yml
packages/loaders/openapi/tests/unknown-properties-union.test.ts

enhance(json-schema): select the best match if none of them is fully matched

---

.changeset/fresh-jars-call.md

No changeset was added to #6037  so this fix was never released.
expected)
- OS:
- NodeJS: …

chore: add string interpolation changeset

---

.changeset/happy-turkeys-press.md
packages/loaders/json-schema/src/addRootFieldResolver.ts
packages/loaders/openapi/tests/fixtures/form-explode.yml
packages/loaders/openapi/tests/form-explode-oneof.test.ts

Handle input unions for query parameters

---

.changeset/real-oranges-do.md
packages/loaders/json-schema/src/addExecutionLogicToComposer.ts
packages/loaders/json-schema/src/getComposerFromJSONSchema.ts
packages/loaders/json-schema/src/types.ts

feat: override single format scalar

---

website/src/pages/docs/guides/hive.mdx

Fixes a typo and a wording issue
Docs changes - typos and wording
Fixes None
N/A
N/A
N/A
N/A
N/A

docs: typos and wording

---

website/src/pages/docs/transforms/hoist.mdx

Changes title
see pr
N/A
N/A
N/A
N/A
N/A

docs: remove wrong wording

---

.changeset/@graphql-mesh_mongoose-6566-dependencies.md
.changeset/itchy-boxes-double.md
packages/handlers/mongoose/package.json
packages/handlers/mongoose/src/index.ts
packages/loaders/openapi/tests/schemas.test.ts
packages/runtime/src/get-mesh.ts
packages/runtime/src/useSubschema.ts
packages/runtime/src/utils.ts

Fixes https://github.com/ardatan/graphql-mesh/issues/6107 
Fixes https://github.com/ardatan/graphql-mesh/issues/6253

Automatically disable JIT when the schema or the env is not compatible

---

.changeset/late-eels-sleep.md
packages/legacy/transforms/hive/src/index.ts

Fixes https://github.com/ardatan/graphql-mesh/issues/6741

fix(transform-hive): support selfHosting options

---

.changeset/spicy-olives-exercise.md
packages/legacy/handlers/supergraph/src/index.ts
packages/legacy/handlers/supergraph/tests/fixtures/service-author/resolvers.ts
packages/legacy/handlers/supergraph/tests/fixtures/service-author/server.ts
packages/legacy/handlers/supergraph/tests/fixtures/service-author/typeDefs.graphql
packages/legacy/handlers/supergraph/tests/fixtures/service-book/resolvers.ts
packages/legacy/handlers/supergraph/tests/fixtures/service-book/server.ts
packages/legacy/handlers/supergraph/tests/fixtures/service-book/typeDefs.graphql
packages/legacy/handlers/supergraph/tests/fixtures/supergraph.graphql
packages/legacy/handlers/supergraph/tests/fixtures/supergraph.yaml
packages/legacy/handlers/supergraph/tests/supergraph.spec.ts
website/src/pages/docs/handlers/supergraph.mdx

- Updates the documentation
- Adds tests for extra configuration for each subgraph with string interpolation to provide values from the context or environment variables

fix(supergraph-handler): handle subgraphs individually with interpolated endpoint and headers

---

packages/loaders/openapi/tests/fixtures/default-values.json
packages/loaders/openapi/tests/schemas.test.ts

Blocked by https://github.com/graphql-compose/graphql-compose/issues/407

Reproduction #6937

---

.changeset/@graphql-mesh_cli-6936-dependencies.md
.changeset/forty-experts-sing.md
.github/workflows/tests.yml
examples/json-schema-example/tests/artifacts.test.ts
packages/legacy/cli/package.json
packages/legacy/cli/src/commands/serve/getGraphQLWSOpts.ts
packages/legacy/cli/src/commands/serve/node-http.ts
packages/legacy/cli/src/commands/serve/serve.ts
packages/legacy/cli/src/commands/serve/types.ts
packages/legacy/cli/src/commands/serve/uWebsockets.ts
packages/legacy/cli/src/index.ts
packages/legacy/runtime/src/types.ts
packages/legacy/utils/src/registerTerminateHandler.ts
packages/serve-cli/src/nodeHttp.ts
packages/serve-cli/src/run.ts
packages/serve-cli/src/types.ts
packages/serve-cli/src/uWebSockets.ts
yarn.lock

enhance(serve): fallback to `node:http` when uWebSockets is not available

---

.changeset/stupid-pets-sneeze.md
packages/legacy/cli/src/index.ts

Fixes https://github.com/ardatan/graphql-mesh/issues/6996

Fix: `mesh build` command ESM compatibility

---

website/src/pages/docs/transforms/type-merging.mdx

Fixes up some grammar and makes it clearer.
I'm learning this tool and the grammar is unclear. I fixed it.
Fixes #7002
- OS:
- NodeJS:
[CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONT …

Cleans up Grammar

---

README.md

docs: add "Created by The Guild" logo to the readme

---

.changeset/early-pants-give.md
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/tests/serve-runtime.spec.ts

Rename the title of GraphiQL to GraphiQL Mesh

enhance(serve-runtime): rename GraphiQL's title to GraphiQL Mesh

---

website/src/pages/docs/guides/hive.mdx

This is for #7243 
expected)
- OS:
- …

Docs: Update Hive SDL urls.

---

.changeset/heavy-lizards-deliver.md
e2e/js-config/__snapshots__/js-config.test.ts.snap
e2e/js-config/js-config.test.ts
e2e/js-config/mesh.config.js
e2e/js-config/package.json
e2e/sqlite-chinook/package.json
packages/compose-cli/src/run.ts
packages/serve-cli/src/run.ts
website/src/pages/v1/compose/index.mdx
website/src/pages/v1/serve/index.mdx
yarn.lock

The current list are the new config defaults, sorted by priority:
- mesh.config.ts
- mesh.config.mts
- mesh.config.cts
- mesh.config.js
- mesh.config.mjs
- mesh.config.cjs

[v1] JS config support and more defaults

---

.changeset/thin-olives-happen.md
.changeset/tiny-radios-love.md
e2e/openapi-naming-convention/__snapshots__/openapi-naming-convention.test.ts.snap
e2e/openapi-naming-convention/mesh.config.ts
e2e/openapi-naming-convention/openapi-naming-convention.test.ts
e2e/openapi-naming-convention/openapi.json
e2e/openapi-naming-convention/package.json
packages/compose-cli/src/getComposedSchemaFromConfig.ts
packages/compose-cli/src/types.ts
packages/fusion/composition/src/transforms/naming-convention.ts
packages/fusion/runtime/src/federation.ts
yarn.lock

Fixes https://github.com/ardatan/graphql-mesh/issues/7229
This PR fixes two bugs;
- Removes root-level transformations which don't work for now, use source-level transforms instead
- Fixes the enum value transformations issues by using `mapSchema` correctly

[v1] fix(runtime): transformations on enum values

---

.github/workflows/release.yml
.github/workflows/tests.yml
.gitignore
docker/Dockerfile
docker/README.md
docker/docker-compose.yml
docker/docker.hcl
docker/package.json
e2e/docker-image/docker-image.test.ts
e2e/docker-image/mesh.config.ts
e2e/utils/tenv.ts
website/src/pages/v1/serve/deployment/docker.mdx
website/src/pages/v1/serve/index.mdx

feat: dockerize mesh serve with hive integration

---

.changeset/@graphql-mesh_fusion-composition-7286-dependencies.md
e2e/openapi-prune/__snapshots__/openapi-prune.test.ts.snap
e2e/openapi-prune/mesh.config.ts
e2e/openapi-prune/openapi-prune.test.ts
e2e/openapi-prune/openapi.json
e2e/openapi-prune/package.json
e2e/openapi-prune/services/Wiki.ts
packages/fusion/composition/package.json
packages/fusion/composition/src/compose.ts
packages/fusion/composition/tests/composition.spec.ts
yarn.lock

Bump utils to fix the bug in `pruneSchema`

---

.changeset/@graphql-mesh_plugin-hive-7300-dependencies.md
.changeset/@graphql-mesh_serve-runtime-7300-dependencies.md
.changeset/@graphql-mesh_transform-hive-7300-dependencies.md
.changeset/tender-frogs-pump.md
packages/legacy/transforms/hive/package.json
packages/legacy/transforms/hive/src/index.ts
packages/plugins/hive/package.json
packages/plugins/hive/src/index.ts
packages/serve-runtime/package.json
packages/serve-runtime/src/createServeRuntime.ts
packages/serve-runtime/src/types.ts
yarn.lock

Closes #7299 and also in legacy Mesh.

Upgrade to use @graphql-hive/yoga

---

.changeset/ninety-shoes-fetch.md
e2e/openapi-arg-rename/__snapshots__/openapi-arg-rename.test.ts.snap
e2e/openapi-arg-rename/mesh.config.ts
e2e/openapi-arg-rename/openapi-arg-rename.test.ts
packages/fusion/runtime/src/federation.ts

Replication, arg rename with field name naming convention

---

.changeset/rich-bears-wonder-2.md
packages/fusion/runtime/src/utils.ts
packages/plugins/hmac-upstream-signature/package.json
packages/plugins/hmac-upstream-signature/src/index.ts
packages/plugins/hmac-upstream-signature/src/useHMACUpstreamSignature.spec.ts
packages/serve-cli/rollup.config.js
website/src/pages/v1/serve/features/auth/jwt.mdx
website/src/pages/v1/serve/features/security/_meta.ts
website/src/pages/v1/serve/features/security/hmac-signature.mdx
website/src/pages/v1/serve/features/security/index.mdx
yarn.lock

feat(plugin): upstream hmac signature

---

.changeset/many-pugs-poke.md
packages/compose-cli/src/run.ts
packages/legacy/utils/src/logger.ts
packages/serve-cli/src/run.ts

Remove emojis from log

---

packages/serve-cli/src/types.ts

Drop MeshServeCLIContext as it should not be used

---

.changeset/@graphql-mesh_fusion-runtime-7482-dependencies.md
.changeset/@graphql-mesh_graphql-7482-dependencies.md
.changeset/@graphql-mesh_serve-runtime-7482-dependencies.md
.changeset/@graphql-mesh_supergraph-7482-dependencies.md
packages/fusion/runtime/package.json
packages/legacy/handlers/graphql/package.json
packages/legacy/handlers/supergraph/package.json
packages/serve-runtime/package.json
yarn.lock

Bump `@graphql-tools/federation`

Bump GraphQL Tools Federation

---

.changeset/slow-toes-marry.md
packages/fusion/runtime/src/utils.ts
packages/loaders/json-schema/src/index.ts
packages/transports/common/src/types.ts
packages/transports/http-callback/src/index.ts
packages/transports/http/src/index.ts
packages/transports/mysql/src/index.ts
packages/transports/neo4j/src/index.ts
packages/transports/rest/src/index.ts
packages/transports/soap/src/index.ts
packages/transports/sqlite/src/index.ts
packages/transports/thrift/src/index.ts
packages/transports/ws/src/index.ts

The kind type has no effect since serve does not bundle any transport.

Transport's kind doesn't need to be typed

---

.changeset/fuzzy-chefs-shop.md
packages/serve-cli/src/index.ts
packages/serve-runtime/src/index.ts
packages/serve-runtime/src/plugins/useCustomAgent.ts
packages/serve-runtime/src/plugins/useSubgraphExecuteDebug.ts
packages/serve-runtime/tests/useCustomAgent.test.ts
website/src/pages/v1/serve/features/security/_meta.ts
website/src/pages/v1/serve/features/security/https.mdx
yarn.lock

New docs for HTTPS & new plugin to use custom HTTP agent
Now it is easier to provide a self signed certificates or disable SSL verification either with Node env vars or a custom HTTP agent

HTTPS Configuration

---

.changeset/red-jars-rule.md
packages/compose-cli/src/getComposedSchemaFromConfig.ts

Better error messages without a stack trace etc for composition and loading errors

enhance(compose-cli): better error messages

---

website/src/pages/_meta.tsx

Hide examples from docs

---

website/src/pages/v1/getting-started.mdx

Fix the onboarding documentation.

Fix the onboarding documentation

---

website/src/pages/v1/transforms/rename.mdx

Fix the 'Rename Transform' documentation.

Fix the 'Rename Transform' documentation

---

.changeset/lazy-forks-sniff.md
examples/grpc-reflection-example/example-queries/GetGreeting.query.graphql
examples/grpc-reflection-example/proto/Playground/playground.proto
examples/grpc-reflection-example/proto/helloworld.proto
examples/grpc-reflection-example/start-server.ts
examples/grpc-reflection-example/tests/__snapshots__/grpc-reflection.test.ts.snap
packages/legacy/handlers/grpc/src/index.ts

Fixes https://github.com/ardatan/graphql-mesh/issues/6847
Fixes https://github.com/ardatan/graphql-mesh/issues/6424

fix(grpc): handle multiple services through reflection

---

.changeset/@graphql-mesh_fusion-runtime-7816-dependencies.md
.changeset/mean-papayas-look.md
.github/workflows/tests.yml
e2e/json-schema-subscriptions/__snapshots__/json-schema-subscriptions.test.ts.snap
e2e/json-schema-subscriptions/json-schema-subscriptions.test.ts
e2e/json-schema-subscriptions/mesh.config.ts
packages/fusion/composition/src/transforms/encapsulate.ts
packages/fusion/runtime/package.json
packages/fusion/runtime/src/federation/subgraph.ts
packages/fusion/runtime/src/federation/supergraph.ts
packages/legacy/config/src/process.ts
packages/legacy/utils/src/resolve-additional-resolvers.ts
packages/serve-runtime/src/createGatewayRuntime.ts
website/src/pages/v1/_meta.ts
website/src/pages/v1/subscriptions-webhooks.mdx
yarn.lock

Fixes https://github.com/ardatan/graphql-mesh/discussions/7760

fix: subscriptions & webhooks

---

.changeset/plenty-trees-live.md
packages/legacy/config/src/process.ts
packages/legacy/config/src/utils.ts
packages/legacy/config/test/processConfig.test.ts
packages/legacy/utils/src/defaultImportFn.ts

Fixes #8149 
Fix support for bundling environments like Next.js
Regression introduced in [#8082](https://github.com/ardatan/graphql-mesh/pull/8082)

fix: bundling env support

---

website/next-env.d.ts
website/src/components/index-page.tsx
website/src/components/run-anywhere-section.tsx

Added [Run Anywhere] section for the new landing page.

Add Run Anywhere section

---

website/theme.config.tsx

fix version dropdown

---

website/src/pages/_meta.tsx
website/theme.config.tsx

Updated the link to go to the new blog.

Update the links to go to Hive blog

---

.changeset/cool-radios-lose.md
packages/cache/inmemory-lru/src/index.ts
packages/cache/inmemory-lru/test/cache.test.ts
packages/legacy/transforms/cache/test/cache.spec.ts

Causes https://github.com/graphql-hive/gateway/pull/1000
Ref GW-290

Fix race condition when getting keys while having multiple sets with a TTL

---

.changeset/polite-colts-study.md
packages/cache/redis/src/index.ts
packages/cache/redis/yaml-config.graphql
packages/legacy/types/src/config-schema.json
packages/legacy/types/src/config.ts
website/src/generated-markdown/RedisConfigCluster.generated.md

Ref GW-386
Cluster support for Redis
Docs [here ](https://github.com/graphql-hive/console/pull/6831)

Redis Cluster Support

---

.github/workflows/website.yml
.gitignore
package.json
website/package.json
website/playwright.config.ts
website/public/codesandbox-iframe.html
website/src/components/examples-sandbox.e2e.ts
website/src/components/examples-sandbox.tsx
yarn.lock

I reinstalled Node and Corepack to make Yarn stop hanging and finally got this test to run :) 
Missing tests for #8768.
Well. I ran Playwright. There is a path in here that will run differently on `master`, but I also ran it by setting the env var directly.

landing codesandbox e2e test

---

.changeset/@graphql-mesh_config-8776-dependencies.md
.changeset/@graphql-mesh_plugin-http-details-extensions-8776-dependencies.md
.changeset/@graphql-mesh_plugin-jit-8776-dependencies.md
.changeset/@graphql-mesh_plugin-live-query-8776-dependencies.md
.changeset/@graphql-mesh_plugin-newrelic-8776-dependencies.md
.changeset/@graphql-mesh_plugin-operation-field-permissions-8776-dependencies.md
.changeset/@graphql-mesh_plugin-rate-limit-8776-dependencies.md
.changeset/@graphql-mesh_plugin-response-cache-8776-dependencies.md
.changeset/@graphql-mesh_plugin-statsd-8776-dependencies.md
.changeset/@graphql-mesh_runtime-8776-dependencies.md
.changeset/yellow-donuts-notice.md
examples/auth0/package.json
examples/spacex-cfw/package.json
examples/v1-next/auth0/package.json
examples/v1-next/integrations/cfw-spacex/package.json
packages/legacy/config/package.json
packages/legacy/runtime/package.json
packages/plugins/http-details-extensions/package.json
packages/plugins/jit/package.json
packages/plugins/live-query/package.json
packages/plugins/mock/package.json
packages/plugins/newrelic/package.json
packages/plugins/operation-field-permissions/package.json
packages/plugins/rate-limit/package.json
packages/plugins/response-cache/package.json
packages/plugins/statsd/package.json
yarn.lock

Related to https://github.com/graphql-hive/gateway/issues/1485 and https://github.com/graphql-hive/envelop/pull/2676.

Bump all envelop packages and improve performance of rate limiter
